// This file was auto-generated by Fern from our API Definition.

package api

// AccessCodesUpdateRequest is an in-lined request used by the Update endpoint.
type AccessCodesUpdateRequest struct {
	Name     *string `json:"name,omitempty"`
	StartsAt *string `json:"starts_at,omitempty"`
	EndsAt   *string `json:"ends_at,omitempty"`
	// <span style="white-space: nowrap">`<= 8 characters`</span>
	Code                    *string                       `json:"code,omitempty"`
	Sync                    *bool                         `json:"sync,omitempty"`
	AttemptForOfflineDevice *bool                         `json:"attempt_for_offline_device,omitempty"`
	PreferNativeScheduling  *bool                         `json:"prefer_native_scheduling,omitempty"`
	UseBackupAccessCodePool *bool                         `json:"use_backup_access_code_pool,omitempty"`
	AccessCodeId            string                        `json:"access_code_id"`
	DeviceId                *string                       `json:"device_id,omitempty"`
	Type                    *AccessCodesUpdateRequestType `json:"type,omitempty"`
}
