// This file was auto-generated by Fern from our API Definition.

package api

// AccessCodesCreateMultipleRequest is an in-lined request used by the CreateMultiple endpoint.
type AccessCodesCreateMultipleRequest struct {
	DeviceIds                      []string                                                        `json:"device_ids,omitempty"`
	BehaviorWhenCodeCannotBeShared *AccessCodesCreateMultipleRequestBehaviorWhenCodeCannotBeShared `json:"behavior_when_code_cannot_be_shared,omitempty"`
	Name                           *string                                                         `json:"name,omitempty"`
	StartsAt                       *string                                                         `json:"starts_at,omitempty"`
	EndsAt                         *string                                                         `json:"ends_at,omitempty"`
	// <span style="white-space: nowrap">`<= 8 characters`</span>
	Code                    *string `json:"code,omitempty"`
	AttemptForOfflineDevice *bool   `json:"attempt_for_offline_device,omitempty"`
	PreferNativeScheduling  *bool   `json:"prefer_native_scheduling,omitempty"`
	UseBackupAccessCodePool *bool   `json:"use_backup_access_code_pool,omitempty"`
}
