// This file was auto-generated by Fern from our API Definition.

package api

type AccessCodesCreateResponse struct {
	ActionAttempt *AccessCodesCreateResponseActionAttempt `json:"action_attempt,omitempty"`
	AccessCode    *AccessCodesCreateResponseAccessCode    `json:"access_code,omitempty"`
	Ok            bool                                    `json:"ok"`
}
