// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

type AccessCodesUnmanagedGetResponseAccessCodeType uint8

const (
	AccessCodesUnmanagedGetResponseAccessCodeTypeTimeBound AccessCodesUnmanagedGetResponseAccessCodeType = iota + 1
	AccessCodesUnmanagedGetResponseAccessCodeTypeOngoing
)

func (a AccessCodesUnmanagedGetResponseAccessCodeType) String() string {
	switch a {
	default:
		return strconv.Itoa(int(a))
	case AccessCodesUnmanagedGetResponseAccessCodeTypeTimeBound:
		return "time_bound"
	case AccessCodesUnmanagedGetResponseAccessCodeTypeOngoing:
		return "ongoing"
	}
}

func (a AccessCodesUnmanagedGetResponseAccessCodeType) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", a.String())), nil
}

func (a *AccessCodesUnmanagedGetResponseAccessCodeType) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "time_bound":
		value := AccessCodesUnmanagedGetResponseAccessCodeTypeTimeBound
		*a = value
	case "ongoing":
		value := AccessCodesUnmanagedGetResponseAccessCodeTypeOngoing
		*a = value
	}
	return nil
}
