// This file was auto-generated by Fern from our API Definition.

package api

type AccessCodesUpdatePutResponseActionAttemptErrorError struct {
	Type    string `json:"type"`
	Message string `json:"message"`
}
