// This file was auto-generated by Fern from our API Definition.

package api

type AccessCode struct {
	CommonCodeKey               *string          `json:"common_code_key,omitempty"`
	IsScheduledOnDevice         *bool            `json:"is_scheduled_on_device,omitempty"`
	Type                        AccessCodeType   `json:"type,omitempty"`
	IsWaitingForCodeAssignment  *bool            `json:"is_waiting_for_code_assignment,omitempty"`
	AccessCodeId                string           `json:"access_code_id"`
	DeviceId                    string           `json:"device_id"`
	Name                        *string          `json:"name,omitempty"`
	Code                        *string          `json:"code,omitempty"`
	CreatedAt                   string           `json:"created_at"`
	Errors                      *any             `json:"errors,omitempty"`
	Warnings                    *any             `json:"warnings,omitempty"`
	IsManaged                   string           `json:"is_managed"`
	StartsAt                    *string          `json:"starts_at,omitempty"`
	EndsAt                      *string          `json:"ends_at,omitempty"`
	Status                      AccessCodeStatus `json:"status,omitempty"`
	IsBackupAccessCodeAvailable bool             `json:"is_backup_access_code_available"`
	IsBackup                    *bool            `json:"is_backup,omitempty"`
	PulledBackupAccessCodeId    *string          `json:"pulled_backup_access_code_id,omitempty"`
}
