// This file was auto-generated by Fern from our API Definition.

package api

type ActionAttemptsGetResponseActionAttemptError struct {
	ActionType      string                                            `json:"action_type"`
	ActionAttemptId string                                            `json:"action_attempt_id"`
	Result          *string                                           `json:"result,omitempty"`
	Error           *ActionAttemptsGetResponseActionAttemptErrorError `json:"error,omitempty"`
}
