// This file was auto-generated by Fern from our API Definition.

package api

type ActionAttemptsListResponse struct {
	ActionAttempts []*ActionAttempt `json:"action_attempts,omitempty"`
	Ok             bool             `json:"ok"`
}
