// This file was auto-generated by Fern from our API Definition.

package api

type ClientSessionsGetResponse struct {
	ClientSession *ClientSession `json:"client_session,omitempty"`
	Ok            bool           `json:"ok"`
}
