// This file was auto-generated by Fern from our API Definition.

package api

type ConnectedAccountUserIdentifier struct {
	Username  *string `json:"username,omitempty"`
	ApiUrl    *string `json:"api_url,omitempty"`
	Email     *string `json:"email,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	Exclusive *bool   `json:"exclusive,omitempty"`
}
