// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

type DevicesListRequestDeviceTypesItemDevicesListRequestDeviceTypesItem uint8

const (
	DevicesListRequestDeviceTypesItemDevicesListRequestDeviceTypesItemEcobeeThermostat DevicesListRequestDeviceTypesItemDevicesListRequestDeviceTypesItem = iota + 1
	DevicesListRequestDeviceTypesItemDevicesListRequestDeviceTypesItemNestThermostat
)

func (d DevicesListRequestDeviceTypesItemDevicesListRequestDeviceTypesItem) String() string {
	switch d {
	default:
		return strconv.Itoa(int(d))
	case DevicesListRequestDeviceTypesItemDevicesListRequestDeviceTypesItemEcobeeThermostat:
		return "ecobee_thermostat"
	case DevicesListRequestDeviceTypesItemDevicesListRequestDeviceTypesItemNestThermostat:
		return "nest_thermostat"
	}
}

func (d DevicesListRequestDeviceTypesItemDevicesListRequestDeviceTypesItem) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", d.String())), nil
}

func (d *DevicesListRequestDeviceTypesItemDevicesListRequestDeviceTypesItem) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "ecobee_thermostat":
		value := DevicesListRequestDeviceTypesItemDevicesListRequestDeviceTypesItemEcobeeThermostat
		*d = value
	case "nest_thermostat":
		value := DevicesListRequestDeviceTypesItemDevicesListRequestDeviceTypesItemNestThermostat
		*d = value
	}
	return nil
}
