// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/seamapi/go/internal"
	time "time"
)

type DevicesDeleteRequest struct {
	DeviceId string `json:"device_id" url:"-"`
}

type DevicesGetRequest struct {
	DeviceId *string `json:"device_id,omitempty" url:"-"`
	Name     *string `json:"name,omitempty" url:"-"`
}

type DevicesListRequest struct {
	// List all devices owned by this connected account
	ConnectedAccountId  *string                                              `json:"connected_account_id,omitempty" url:"-"`
	ConnectedAccountIds []string                                             `json:"connected_account_ids,omitempty" url:"-"`
	ConnectWebviewId    *string                                              `json:"connect_webview_id,omitempty" url:"-"`
	DeviceType          *DeviceType                                          `json:"device_type,omitempty" url:"-"`
	DeviceTypes         []DeviceType                                         `json:"device_types,omitempty" url:"-"`
	Manufacturer        *Manufacturer                                        `json:"manufacturer,omitempty" url:"-"`
	DeviceIds           []string                                             `json:"device_ids,omitempty" url:"-"`
	Limit               *float64                                             `json:"limit,omitempty" url:"-"`
	CreatedBefore       *time.Time                                           `json:"created_before,omitempty" url:"-"`
	UserIdentifierKey   *string                                              `json:"user_identifier_key,omitempty" url:"-"`
	CustomMetadataHas   map[string]*DevicesListRequestCustomMetadataHasValue `json:"custom_metadata_has,omitempty" url:"-"`
	IncludeIf           []DevicesListRequestIncludeIfItem                    `json:"include_if,omitempty" url:"-"`
	ExcludeIf           []DevicesListRequestExcludeIfItem                    `json:"exclude_if,omitempty" url:"-"`
}

func (d *DevicesListRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler DevicesListRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*d = DevicesListRequest(body)
	return nil
}

func (d *DevicesListRequest) MarshalJSON() ([]byte, error) {
	type embed DevicesListRequest
	var marshaler = struct {
		embed
		CreatedBefore *internal.DateTime `json:"created_before,omitempty"`
	}{
		embed:         embed(*d),
		CreatedBefore: internal.NewOptionalDateTime(d.CreatedBefore),
	}
	return json.Marshal(marshaler)
}

type DevicesListDeviceProvidersRequest struct {
	ProviderCategory *ProviderCategory `json:"provider_category,omitempty" url:"-"`
}

type DeviceProvider struct {
	DeviceProviderName DeviceProviderDeviceProviderName       `json:"device_provider_name" url:"device_provider_name"`
	DisplayName        string                                 `json:"display_name" url:"display_name"`
	ImageUrl           string                                 `json:"image_url" url:"image_url"`
	ProviderCategories []DeviceProviderProviderCategoriesItem `json:"provider_categories,omitempty" url:"provider_categories,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeviceProvider) GetDeviceProviderName() DeviceProviderDeviceProviderName {
	if d == nil {
		return ""
	}
	return d.DeviceProviderName
}

func (d *DeviceProvider) GetDisplayName() string {
	if d == nil {
		return ""
	}
	return d.DisplayName
}

func (d *DeviceProvider) GetImageUrl() string {
	if d == nil {
		return ""
	}
	return d.ImageUrl
}

func (d *DeviceProvider) GetProviderCategories() []DeviceProviderProviderCategoriesItem {
	if d == nil {
		return nil
	}
	return d.ProviderCategories
}

func (d *DeviceProvider) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DeviceProvider) UnmarshalJSON(data []byte) error {
	type unmarshaler DeviceProvider
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeviceProvider(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceProvider) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeviceProviderDeviceProviderName string

const (
	DeviceProviderDeviceProviderNameAkuvox                     DeviceProviderDeviceProviderName = "akuvox"
	DeviceProviderDeviceProviderNameAugust                     DeviceProviderDeviceProviderName = "august"
	DeviceProviderDeviceProviderNameAvigilonAlta               DeviceProviderDeviceProviderName = "avigilon_alta"
	DeviceProviderDeviceProviderNameBrivo                      DeviceProviderDeviceProviderName = "brivo"
	DeviceProviderDeviceProviderNameButterflymx                DeviceProviderDeviceProviderName = "butterflymx"
	DeviceProviderDeviceProviderNameSchlage                    DeviceProviderDeviceProviderName = "schlage"
	DeviceProviderDeviceProviderNameSmartthings                DeviceProviderDeviceProviderName = "smartthings"
	DeviceProviderDeviceProviderNameYale                       DeviceProviderDeviceProviderName = "yale"
	DeviceProviderDeviceProviderNameGenie                      DeviceProviderDeviceProviderName = "genie"
	DeviceProviderDeviceProviderNameDoorking                   DeviceProviderDeviceProviderName = "doorking"
	DeviceProviderDeviceProviderNameSalto                      DeviceProviderDeviceProviderName = "salto"
	DeviceProviderDeviceProviderNameLockly                     DeviceProviderDeviceProviderName = "lockly"
	DeviceProviderDeviceProviderNameTtlock                     DeviceProviderDeviceProviderName = "ttlock"
	DeviceProviderDeviceProviderNameLinear                     DeviceProviderDeviceProviderName = "linear"
	DeviceProviderDeviceProviderNameNoiseaware                 DeviceProviderDeviceProviderName = "noiseaware"
	DeviceProviderDeviceProviderNameNuki                       DeviceProviderDeviceProviderName = "nuki"
	DeviceProviderDeviceProviderNameSeamRelayAdmin             DeviceProviderDeviceProviderName = "seam_relay_admin"
	DeviceProviderDeviceProviderNameIgloo                      DeviceProviderDeviceProviderName = "igloo"
	DeviceProviderDeviceProviderNameKwikset                    DeviceProviderDeviceProviderName = "kwikset"
	DeviceProviderDeviceProviderNameMinut                      DeviceProviderDeviceProviderName = "minut"
	DeviceProviderDeviceProviderNameMy2N                       DeviceProviderDeviceProviderName = "my_2n"
	DeviceProviderDeviceProviderNameControlbyweb               DeviceProviderDeviceProviderName = "controlbyweb"
	DeviceProviderDeviceProviderNameNest                       DeviceProviderDeviceProviderName = "nest"
	DeviceProviderDeviceProviderNameIgloohome                  DeviceProviderDeviceProviderName = "igloohome"
	DeviceProviderDeviceProviderNameEcobee                     DeviceProviderDeviceProviderName = "ecobee"
	DeviceProviderDeviceProviderNameHubitat                    DeviceProviderDeviceProviderName = "hubitat"
	DeviceProviderDeviceProviderNameFourSuites                 DeviceProviderDeviceProviderName = "four_suites"
	DeviceProviderDeviceProviderNameDormakabaOracode           DeviceProviderDeviceProviderName = "dormakaba_oracode"
	DeviceProviderDeviceProviderNamePti                        DeviceProviderDeviceProviderName = "pti"
	DeviceProviderDeviceProviderNameWyze                       DeviceProviderDeviceProviderName = "wyze"
	DeviceProviderDeviceProviderNameSeamPassport               DeviceProviderDeviceProviderName = "seam_passport"
	DeviceProviderDeviceProviderNameVisionline                 DeviceProviderDeviceProviderName = "visionline"
	DeviceProviderDeviceProviderNameAssaAbloyCredentialService DeviceProviderDeviceProviderName = "assa_abloy_credential_service"
	DeviceProviderDeviceProviderNameSeamBridge                 DeviceProviderDeviceProviderName = "seam_bridge"
	DeviceProviderDeviceProviderNameTedee                      DeviceProviderDeviceProviderName = "tedee"
	DeviceProviderDeviceProviderNameHoneywellResideo           DeviceProviderDeviceProviderName = "honeywell_resideo"
	DeviceProviderDeviceProviderNameLatch                      DeviceProviderDeviceProviderName = "latch"
)

func NewDeviceProviderDeviceProviderNameFromString(s string) (DeviceProviderDeviceProviderName, error) {
	switch s {
	case "akuvox":
		return DeviceProviderDeviceProviderNameAkuvox, nil
	case "august":
		return DeviceProviderDeviceProviderNameAugust, nil
	case "avigilon_alta":
		return DeviceProviderDeviceProviderNameAvigilonAlta, nil
	case "brivo":
		return DeviceProviderDeviceProviderNameBrivo, nil
	case "butterflymx":
		return DeviceProviderDeviceProviderNameButterflymx, nil
	case "schlage":
		return DeviceProviderDeviceProviderNameSchlage, nil
	case "smartthings":
		return DeviceProviderDeviceProviderNameSmartthings, nil
	case "yale":
		return DeviceProviderDeviceProviderNameYale, nil
	case "genie":
		return DeviceProviderDeviceProviderNameGenie, nil
	case "doorking":
		return DeviceProviderDeviceProviderNameDoorking, nil
	case "salto":
		return DeviceProviderDeviceProviderNameSalto, nil
	case "lockly":
		return DeviceProviderDeviceProviderNameLockly, nil
	case "ttlock":
		return DeviceProviderDeviceProviderNameTtlock, nil
	case "linear":
		return DeviceProviderDeviceProviderNameLinear, nil
	case "noiseaware":
		return DeviceProviderDeviceProviderNameNoiseaware, nil
	case "nuki":
		return DeviceProviderDeviceProviderNameNuki, nil
	case "seam_relay_admin":
		return DeviceProviderDeviceProviderNameSeamRelayAdmin, nil
	case "igloo":
		return DeviceProviderDeviceProviderNameIgloo, nil
	case "kwikset":
		return DeviceProviderDeviceProviderNameKwikset, nil
	case "minut":
		return DeviceProviderDeviceProviderNameMinut, nil
	case "my_2n":
		return DeviceProviderDeviceProviderNameMy2N, nil
	case "controlbyweb":
		return DeviceProviderDeviceProviderNameControlbyweb, nil
	case "nest":
		return DeviceProviderDeviceProviderNameNest, nil
	case "igloohome":
		return DeviceProviderDeviceProviderNameIgloohome, nil
	case "ecobee":
		return DeviceProviderDeviceProviderNameEcobee, nil
	case "hubitat":
		return DeviceProviderDeviceProviderNameHubitat, nil
	case "four_suites":
		return DeviceProviderDeviceProviderNameFourSuites, nil
	case "dormakaba_oracode":
		return DeviceProviderDeviceProviderNameDormakabaOracode, nil
	case "pti":
		return DeviceProviderDeviceProviderNamePti, nil
	case "wyze":
		return DeviceProviderDeviceProviderNameWyze, nil
	case "seam_passport":
		return DeviceProviderDeviceProviderNameSeamPassport, nil
	case "visionline":
		return DeviceProviderDeviceProviderNameVisionline, nil
	case "assa_abloy_credential_service":
		return DeviceProviderDeviceProviderNameAssaAbloyCredentialService, nil
	case "seam_bridge":
		return DeviceProviderDeviceProviderNameSeamBridge, nil
	case "tedee":
		return DeviceProviderDeviceProviderNameTedee, nil
	case "honeywell_resideo":
		return DeviceProviderDeviceProviderNameHoneywellResideo, nil
	case "latch":
		return DeviceProviderDeviceProviderNameLatch, nil
	}
	var t DeviceProviderDeviceProviderName
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceProviderDeviceProviderName) Ptr() *DeviceProviderDeviceProviderName {
	return &d
}

type DeviceProviderProviderCategoriesItem string

const (
	DeviceProviderProviderCategoriesItemStable               DeviceProviderProviderCategoriesItem = "stable"
	DeviceProviderProviderCategoriesItemConsumerSmartlocks   DeviceProviderProviderCategoriesItem = "consumer_smartlocks"
	DeviceProviderProviderCategoriesItemThermostats          DeviceProviderProviderCategoriesItem = "thermostats"
	DeviceProviderProviderCategoriesItemNoiseSensors         DeviceProviderProviderCategoriesItem = "noise_sensors"
	DeviceProviderProviderCategoriesItemAccessControlSystems DeviceProviderProviderCategoriesItem = "access_control_systems"
)

func NewDeviceProviderProviderCategoriesItemFromString(s string) (DeviceProviderProviderCategoriesItem, error) {
	switch s {
	case "stable":
		return DeviceProviderProviderCategoriesItemStable, nil
	case "consumer_smartlocks":
		return DeviceProviderProviderCategoriesItemConsumerSmartlocks, nil
	case "thermostats":
		return DeviceProviderProviderCategoriesItemThermostats, nil
	case "noise_sensors":
		return DeviceProviderProviderCategoriesItemNoiseSensors, nil
	case "access_control_systems":
		return DeviceProviderProviderCategoriesItemAccessControlSystems, nil
	}
	var t DeviceProviderProviderCategoriesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceProviderProviderCategoriesItem) Ptr() *DeviceProviderProviderCategoriesItem {
	return &d
}

type DevicesDeleteResponse struct {
	Ok bool `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DevicesDeleteResponse) GetOk() bool {
	if d == nil {
		return false
	}
	return d.Ok
}

func (d *DevicesDeleteResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DevicesDeleteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DevicesDeleteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DevicesDeleteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DevicesDeleteResponse) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DevicesGetResponse struct {
	Device *Device `json:"device,omitempty" url:"device,omitempty"`
	Ok     bool    `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DevicesGetResponse) GetDevice() *Device {
	if d == nil {
		return nil
	}
	return d.Device
}

func (d *DevicesGetResponse) GetOk() bool {
	if d == nil {
		return false
	}
	return d.Ok
}

func (d *DevicesGetResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DevicesGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DevicesGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DevicesGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DevicesGetResponse) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DevicesListDeviceProvidersResponse struct {
	DeviceProviders []*DeviceProvider `json:"device_providers,omitempty" url:"device_providers,omitempty"`
	Ok              bool              `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DevicesListDeviceProvidersResponse) GetDeviceProviders() []*DeviceProvider {
	if d == nil {
		return nil
	}
	return d.DeviceProviders
}

func (d *DevicesListDeviceProvidersResponse) GetOk() bool {
	if d == nil {
		return false
	}
	return d.Ok
}

func (d *DevicesListDeviceProvidersResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DevicesListDeviceProvidersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DevicesListDeviceProvidersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DevicesListDeviceProvidersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DevicesListDeviceProvidersResponse) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DevicesListRequestCustomMetadataHasValue struct {
	String  string
	Boolean bool

	typ string
}

func NewDevicesListRequestCustomMetadataHasValueFromString(value string) *DevicesListRequestCustomMetadataHasValue {
	return &DevicesListRequestCustomMetadataHasValue{typ: "String", String: value}
}

func NewDevicesListRequestCustomMetadataHasValueFromBoolean(value bool) *DevicesListRequestCustomMetadataHasValue {
	return &DevicesListRequestCustomMetadataHasValue{typ: "Boolean", Boolean: value}
}

func (d *DevicesListRequestCustomMetadataHasValue) GetString() string {
	if d == nil {
		return ""
	}
	return d.String
}

func (d *DevicesListRequestCustomMetadataHasValue) GetBoolean() bool {
	if d == nil {
		return false
	}
	return d.Boolean
}

func (d *DevicesListRequestCustomMetadataHasValue) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		d.typ = "String"
		d.String = valueString
		return nil
	}
	var valueBoolean bool
	if err := json.Unmarshal(data, &valueBoolean); err == nil {
		d.typ = "Boolean"
		d.Boolean = valueBoolean
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, d)
}

func (d DevicesListRequestCustomMetadataHasValue) MarshalJSON() ([]byte, error) {
	if d.typ == "String" || d.String != "" {
		return json.Marshal(d.String)
	}
	if d.typ == "Boolean" || d.Boolean != false {
		return json.Marshal(d.Boolean)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", d)
}

type DevicesListRequestCustomMetadataHasValueVisitor interface {
	VisitString(string) error
	VisitBoolean(bool) error
}

func (d *DevicesListRequestCustomMetadataHasValue) Accept(visitor DevicesListRequestCustomMetadataHasValueVisitor) error {
	if d.typ == "String" || d.String != "" {
		return visitor.VisitString(d.String)
	}
	if d.typ == "Boolean" || d.Boolean != false {
		return visitor.VisitBoolean(d.Boolean)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", d)
}

type DevicesListRequestExcludeIfItem string

const (
	DevicesListRequestExcludeIfItemCanRemotelyUnlock            DevicesListRequestExcludeIfItem = "can_remotely_unlock"
	DevicesListRequestExcludeIfItemCanRemotelyLock              DevicesListRequestExcludeIfItem = "can_remotely_lock"
	DevicesListRequestExcludeIfItemCanProgramOfflineAccessCodes DevicesListRequestExcludeIfItem = "can_program_offline_access_codes"
	DevicesListRequestExcludeIfItemCanProgramOnlineAccessCodes  DevicesListRequestExcludeIfItem = "can_program_online_access_codes"
	DevicesListRequestExcludeIfItemCanSimulateRemoval           DevicesListRequestExcludeIfItem = "can_simulate_removal"
	DevicesListRequestExcludeIfItemCanSimulateConnection        DevicesListRequestExcludeIfItem = "can_simulate_connection"
	DevicesListRequestExcludeIfItemCanSimulateDisconnection     DevicesListRequestExcludeIfItem = "can_simulate_disconnection"
)

func NewDevicesListRequestExcludeIfItemFromString(s string) (DevicesListRequestExcludeIfItem, error) {
	switch s {
	case "can_remotely_unlock":
		return DevicesListRequestExcludeIfItemCanRemotelyUnlock, nil
	case "can_remotely_lock":
		return DevicesListRequestExcludeIfItemCanRemotelyLock, nil
	case "can_program_offline_access_codes":
		return DevicesListRequestExcludeIfItemCanProgramOfflineAccessCodes, nil
	case "can_program_online_access_codes":
		return DevicesListRequestExcludeIfItemCanProgramOnlineAccessCodes, nil
	case "can_simulate_removal":
		return DevicesListRequestExcludeIfItemCanSimulateRemoval, nil
	case "can_simulate_connection":
		return DevicesListRequestExcludeIfItemCanSimulateConnection, nil
	case "can_simulate_disconnection":
		return DevicesListRequestExcludeIfItemCanSimulateDisconnection, nil
	}
	var t DevicesListRequestExcludeIfItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DevicesListRequestExcludeIfItem) Ptr() *DevicesListRequestExcludeIfItem {
	return &d
}

type DevicesListRequestIncludeIfItem string

const (
	DevicesListRequestIncludeIfItemCanRemotelyUnlock            DevicesListRequestIncludeIfItem = "can_remotely_unlock"
	DevicesListRequestIncludeIfItemCanRemotelyLock              DevicesListRequestIncludeIfItem = "can_remotely_lock"
	DevicesListRequestIncludeIfItemCanProgramOfflineAccessCodes DevicesListRequestIncludeIfItem = "can_program_offline_access_codes"
	DevicesListRequestIncludeIfItemCanProgramOnlineAccessCodes  DevicesListRequestIncludeIfItem = "can_program_online_access_codes"
	DevicesListRequestIncludeIfItemCanSimulateRemoval           DevicesListRequestIncludeIfItem = "can_simulate_removal"
	DevicesListRequestIncludeIfItemCanSimulateConnection        DevicesListRequestIncludeIfItem = "can_simulate_connection"
	DevicesListRequestIncludeIfItemCanSimulateDisconnection     DevicesListRequestIncludeIfItem = "can_simulate_disconnection"
)

func NewDevicesListRequestIncludeIfItemFromString(s string) (DevicesListRequestIncludeIfItem, error) {
	switch s {
	case "can_remotely_unlock":
		return DevicesListRequestIncludeIfItemCanRemotelyUnlock, nil
	case "can_remotely_lock":
		return DevicesListRequestIncludeIfItemCanRemotelyLock, nil
	case "can_program_offline_access_codes":
		return DevicesListRequestIncludeIfItemCanProgramOfflineAccessCodes, nil
	case "can_program_online_access_codes":
		return DevicesListRequestIncludeIfItemCanProgramOnlineAccessCodes, nil
	case "can_simulate_removal":
		return DevicesListRequestIncludeIfItemCanSimulateRemoval, nil
	case "can_simulate_connection":
		return DevicesListRequestIncludeIfItemCanSimulateConnection, nil
	case "can_simulate_disconnection":
		return DevicesListRequestIncludeIfItemCanSimulateDisconnection, nil
	}
	var t DevicesListRequestIncludeIfItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DevicesListRequestIncludeIfItem) Ptr() *DevicesListRequestIncludeIfItem {
	return &d
}

type DevicesListResponse struct {
	Devices []*Device `json:"devices,omitempty" url:"devices,omitempty"`
	Ok      bool      `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DevicesListResponse) GetDevices() []*Device {
	if d == nil {
		return nil
	}
	return d.Devices
}

func (d *DevicesListResponse) GetOk() bool {
	if d == nil {
		return false
	}
	return d.Ok
}

func (d *DevicesListResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DevicesListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DevicesListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DevicesListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DevicesListResponse) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DevicesUpdateRequestCustomMetadataValue struct {
	String  string
	Boolean bool

	typ string
}

func NewDevicesUpdateRequestCustomMetadataValueFromString(value string) *DevicesUpdateRequestCustomMetadataValue {
	return &DevicesUpdateRequestCustomMetadataValue{typ: "String", String: value}
}

func NewDevicesUpdateRequestCustomMetadataValueFromBoolean(value bool) *DevicesUpdateRequestCustomMetadataValue {
	return &DevicesUpdateRequestCustomMetadataValue{typ: "Boolean", Boolean: value}
}

func (d *DevicesUpdateRequestCustomMetadataValue) GetString() string {
	if d == nil {
		return ""
	}
	return d.String
}

func (d *DevicesUpdateRequestCustomMetadataValue) GetBoolean() bool {
	if d == nil {
		return false
	}
	return d.Boolean
}

func (d *DevicesUpdateRequestCustomMetadataValue) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		d.typ = "String"
		d.String = valueString
		return nil
	}
	var valueBoolean bool
	if err := json.Unmarshal(data, &valueBoolean); err == nil {
		d.typ = "Boolean"
		d.Boolean = valueBoolean
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, d)
}

func (d DevicesUpdateRequestCustomMetadataValue) MarshalJSON() ([]byte, error) {
	if d.typ == "String" || d.String != "" {
		return json.Marshal(d.String)
	}
	if d.typ == "Boolean" || d.Boolean != false {
		return json.Marshal(d.Boolean)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", d)
}

type DevicesUpdateRequestCustomMetadataValueVisitor interface {
	VisitString(string) error
	VisitBoolean(bool) error
}

func (d *DevicesUpdateRequestCustomMetadataValue) Accept(visitor DevicesUpdateRequestCustomMetadataValueVisitor) error {
	if d.typ == "String" || d.String != "" {
		return visitor.VisitString(d.String)
	}
	if d.typ == "Boolean" || d.Boolean != false {
		return visitor.VisitBoolean(d.Boolean)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", d)
}

type DevicesUpdateRequestProperties struct {
	Name *string `json:"name,omitempty" url:"name,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DevicesUpdateRequestProperties) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}

func (d *DevicesUpdateRequestProperties) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DevicesUpdateRequestProperties) UnmarshalJSON(data []byte) error {
	type unmarshaler DevicesUpdateRequestProperties
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DevicesUpdateRequestProperties(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DevicesUpdateRequestProperties) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DevicesUpdateResponse struct {
	Ok bool `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DevicesUpdateResponse) GetOk() bool {
	if d == nil {
		return false
	}
	return d.Ok
}

func (d *DevicesUpdateResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DevicesUpdateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DevicesUpdateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DevicesUpdateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DevicesUpdateResponse) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DevicesUpdateRequest struct {
	DeviceId       string                                              `json:"device_id" url:"-"`
	Properties     *DevicesUpdateRequestProperties                     `json:"properties,omitempty" url:"-"`
	Name           *string                                             `json:"name,omitempty" url:"-"`
	IsManaged      *bool                                               `json:"is_managed,omitempty" url:"-"`
	CustomMetadata map[string]*DevicesUpdateRequestCustomMetadataValue `json:"custom_metadata,omitempty" url:"-"`
}
