// This file was auto-generated by Fern from our API Definition.

package api

// LocksLockDoorRequest is an in-lined request used by the LockDoor endpoint.
type LocksLockDoorRequest struct {
	DeviceId string `json:"device_id"`
	Sync     *bool  `json:"sync,omitempty"`
}
