// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/seamapi/go/internal"
	time "time"
)

type LocksGetRequest struct {
	DeviceId *string `json:"device_id,omitempty" url:"-"`
	Name     *string `json:"name,omitempty" url:"-"`
}

type LocksListRequest struct {
	// List all devices owned by this connected account
	ConnectedAccountId  *string                                            `json:"connected_account_id,omitempty" url:"-"`
	ConnectedAccountIds []string                                           `json:"connected_account_ids,omitempty" url:"-"`
	ConnectWebviewId    *string                                            `json:"connect_webview_id,omitempty" url:"-"`
	DeviceType          *DeviceType                                        `json:"device_type,omitempty" url:"-"`
	DeviceTypes         []DeviceType                                       `json:"device_types,omitempty" url:"-"`
	Manufacturer        *Manufacturer                                      `json:"manufacturer,omitempty" url:"-"`
	DeviceIds           []string                                           `json:"device_ids,omitempty" url:"-"`
	Limit               *float64                                           `json:"limit,omitempty" url:"-"`
	CreatedBefore       *time.Time                                         `json:"created_before,omitempty" url:"-"`
	UserIdentifierKey   *string                                            `json:"user_identifier_key,omitempty" url:"-"`
	CustomMetadataHas   map[string]*LocksListRequestCustomMetadataHasValue `json:"custom_metadata_has,omitempty" url:"-"`
	IncludeIf           []LocksListRequestIncludeIfItem                    `json:"include_if,omitempty" url:"-"`
	ExcludeIf           []LocksListRequestExcludeIfItem                    `json:"exclude_if,omitempty" url:"-"`
}

func (l *LocksListRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler LocksListRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*l = LocksListRequest(body)
	return nil
}

func (l *LocksListRequest) MarshalJSON() ([]byte, error) {
	type embed LocksListRequest
	var marshaler = struct {
		embed
		CreatedBefore *internal.DateTime `json:"created_before,omitempty"`
	}{
		embed:         embed(*l),
		CreatedBefore: internal.NewOptionalDateTime(l.CreatedBefore),
	}
	return json.Marshal(marshaler)
}

type LocksLockDoorRequest struct {
	DeviceId string `json:"device_id" url:"-"`
	Sync     *bool  `json:"sync,omitempty" url:"-"`
}

type LocksGetResponse struct {
	Lock   *Device `json:"lock,omitempty" url:"lock,omitempty"`
	Device *Device `json:"device,omitempty" url:"device,omitempty"`
	Ok     bool    `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LocksGetResponse) GetLock() *Device {
	if l == nil {
		return nil
	}
	return l.Lock
}

func (l *LocksGetResponse) GetDevice() *Device {
	if l == nil {
		return nil
	}
	return l.Device
}

func (l *LocksGetResponse) GetOk() bool {
	if l == nil {
		return false
	}
	return l.Ok
}

func (l *LocksGetResponse) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *LocksGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler LocksGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LocksGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LocksGetResponse) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type LocksListRequestCustomMetadataHasValue struct {
	String  string
	Boolean bool

	typ string
}

func NewLocksListRequestCustomMetadataHasValueFromString(value string) *LocksListRequestCustomMetadataHasValue {
	return &LocksListRequestCustomMetadataHasValue{typ: "String", String: value}
}

func NewLocksListRequestCustomMetadataHasValueFromBoolean(value bool) *LocksListRequestCustomMetadataHasValue {
	return &LocksListRequestCustomMetadataHasValue{typ: "Boolean", Boolean: value}
}

func (l *LocksListRequestCustomMetadataHasValue) GetString() string {
	if l == nil {
		return ""
	}
	return l.String
}

func (l *LocksListRequestCustomMetadataHasValue) GetBoolean() bool {
	if l == nil {
		return false
	}
	return l.Boolean
}

func (l *LocksListRequestCustomMetadataHasValue) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		l.typ = "String"
		l.String = valueString
		return nil
	}
	var valueBoolean bool
	if err := json.Unmarshal(data, &valueBoolean); err == nil {
		l.typ = "Boolean"
		l.Boolean = valueBoolean
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, l)
}

func (l LocksListRequestCustomMetadataHasValue) MarshalJSON() ([]byte, error) {
	if l.typ == "String" || l.String != "" {
		return json.Marshal(l.String)
	}
	if l.typ == "Boolean" || l.Boolean != false {
		return json.Marshal(l.Boolean)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", l)
}

type LocksListRequestCustomMetadataHasValueVisitor interface {
	VisitString(string) error
	VisitBoolean(bool) error
}

func (l *LocksListRequestCustomMetadataHasValue) Accept(visitor LocksListRequestCustomMetadataHasValueVisitor) error {
	if l.typ == "String" || l.String != "" {
		return visitor.VisitString(l.String)
	}
	if l.typ == "Boolean" || l.Boolean != false {
		return visitor.VisitBoolean(l.Boolean)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", l)
}

type LocksListRequestExcludeIfItem string

const (
	LocksListRequestExcludeIfItemCanRemotelyUnlock            LocksListRequestExcludeIfItem = "can_remotely_unlock"
	LocksListRequestExcludeIfItemCanRemotelyLock              LocksListRequestExcludeIfItem = "can_remotely_lock"
	LocksListRequestExcludeIfItemCanProgramOfflineAccessCodes LocksListRequestExcludeIfItem = "can_program_offline_access_codes"
	LocksListRequestExcludeIfItemCanProgramOnlineAccessCodes  LocksListRequestExcludeIfItem = "can_program_online_access_codes"
	LocksListRequestExcludeIfItemCanSimulateRemoval           LocksListRequestExcludeIfItem = "can_simulate_removal"
	LocksListRequestExcludeIfItemCanSimulateConnection        LocksListRequestExcludeIfItem = "can_simulate_connection"
	LocksListRequestExcludeIfItemCanSimulateDisconnection     LocksListRequestExcludeIfItem = "can_simulate_disconnection"
)

func NewLocksListRequestExcludeIfItemFromString(s string) (LocksListRequestExcludeIfItem, error) {
	switch s {
	case "can_remotely_unlock":
		return LocksListRequestExcludeIfItemCanRemotelyUnlock, nil
	case "can_remotely_lock":
		return LocksListRequestExcludeIfItemCanRemotelyLock, nil
	case "can_program_offline_access_codes":
		return LocksListRequestExcludeIfItemCanProgramOfflineAccessCodes, nil
	case "can_program_online_access_codes":
		return LocksListRequestExcludeIfItemCanProgramOnlineAccessCodes, nil
	case "can_simulate_removal":
		return LocksListRequestExcludeIfItemCanSimulateRemoval, nil
	case "can_simulate_connection":
		return LocksListRequestExcludeIfItemCanSimulateConnection, nil
	case "can_simulate_disconnection":
		return LocksListRequestExcludeIfItemCanSimulateDisconnection, nil
	}
	var t LocksListRequestExcludeIfItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l LocksListRequestExcludeIfItem) Ptr() *LocksListRequestExcludeIfItem {
	return &l
}

type LocksListRequestIncludeIfItem string

const (
	LocksListRequestIncludeIfItemCanRemotelyUnlock            LocksListRequestIncludeIfItem = "can_remotely_unlock"
	LocksListRequestIncludeIfItemCanRemotelyLock              LocksListRequestIncludeIfItem = "can_remotely_lock"
	LocksListRequestIncludeIfItemCanProgramOfflineAccessCodes LocksListRequestIncludeIfItem = "can_program_offline_access_codes"
	LocksListRequestIncludeIfItemCanProgramOnlineAccessCodes  LocksListRequestIncludeIfItem = "can_program_online_access_codes"
	LocksListRequestIncludeIfItemCanSimulateRemoval           LocksListRequestIncludeIfItem = "can_simulate_removal"
	LocksListRequestIncludeIfItemCanSimulateConnection        LocksListRequestIncludeIfItem = "can_simulate_connection"
	LocksListRequestIncludeIfItemCanSimulateDisconnection     LocksListRequestIncludeIfItem = "can_simulate_disconnection"
)

func NewLocksListRequestIncludeIfItemFromString(s string) (LocksListRequestIncludeIfItem, error) {
	switch s {
	case "can_remotely_unlock":
		return LocksListRequestIncludeIfItemCanRemotelyUnlock, nil
	case "can_remotely_lock":
		return LocksListRequestIncludeIfItemCanRemotelyLock, nil
	case "can_program_offline_access_codes":
		return LocksListRequestIncludeIfItemCanProgramOfflineAccessCodes, nil
	case "can_program_online_access_codes":
		return LocksListRequestIncludeIfItemCanProgramOnlineAccessCodes, nil
	case "can_simulate_removal":
		return LocksListRequestIncludeIfItemCanSimulateRemoval, nil
	case "can_simulate_connection":
		return LocksListRequestIncludeIfItemCanSimulateConnection, nil
	case "can_simulate_disconnection":
		return LocksListRequestIncludeIfItemCanSimulateDisconnection, nil
	}
	var t LocksListRequestIncludeIfItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l LocksListRequestIncludeIfItem) Ptr() *LocksListRequestIncludeIfItem {
	return &l
}

type LocksListResponse struct {
	Locks   []*Device `json:"locks,omitempty" url:"locks,omitempty"`
	Devices []*Device `json:"devices,omitempty" url:"devices,omitempty"`
	Ok      bool      `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LocksListResponse) GetLocks() []*Device {
	if l == nil {
		return nil
	}
	return l.Locks
}

func (l *LocksListResponse) GetDevices() []*Device {
	if l == nil {
		return nil
	}
	return l.Devices
}

func (l *LocksListResponse) GetOk() bool {
	if l == nil {
		return false
	}
	return l.Ok
}

func (l *LocksListResponse) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *LocksListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler LocksListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LocksListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LocksListResponse) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type LocksLockDoorResponse struct {
	ActionAttempt *ActionAttempt `json:"action_attempt,omitempty" url:"action_attempt,omitempty"`
	Ok            bool           `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LocksLockDoorResponse) GetActionAttempt() *ActionAttempt {
	if l == nil {
		return nil
	}
	return l.ActionAttempt
}

func (l *LocksLockDoorResponse) GetOk() bool {
	if l == nil {
		return false
	}
	return l.Ok
}

func (l *LocksLockDoorResponse) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *LocksLockDoorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler LocksLockDoorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LocksLockDoorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LocksLockDoorResponse) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type LocksUnlockDoorResponse struct {
	ActionAttempt *ActionAttempt `json:"action_attempt,omitempty" url:"action_attempt,omitempty"`
	Ok            bool           `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LocksUnlockDoorResponse) GetActionAttempt() *ActionAttempt {
	if l == nil {
		return nil
	}
	return l.ActionAttempt
}

func (l *LocksUnlockDoorResponse) GetOk() bool {
	if l == nil {
		return false
	}
	return l.Ok
}

func (l *LocksUnlockDoorResponse) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *LocksUnlockDoorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler LocksUnlockDoorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LocksUnlockDoorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LocksUnlockDoorResponse) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type LocksUnlockDoorRequest struct {
	DeviceId string `json:"device_id" url:"-"`
	Sync     *bool  `json:"sync,omitempty" url:"-"`
}
