// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

type LocksListRequestManufacturer uint8

const (
	LocksListRequestManufacturerAkuvox LocksListRequestManufacturer = iota + 1
	LocksListRequestManufacturerAugust
	LocksListRequestManufacturerBrivo
	LocksListRequestManufacturerButterflymx
	LocksListRequestManufacturerDoorking
	LocksListRequestManufacturerGenie
	LocksListRequestManufacturerIgloo
	LocksListRequestManufacturerKeywe
	LocksListRequestManufacturerKwikset
	LocksListRequestManufacturerLinear
	LocksListRequestManufacturerLockly
	LocksListRequestManufacturerNuki
	LocksListRequestManufacturerPhilia
	LocksListRequestManufacturerSalto
	LocksListRequestManufacturerSamsung
	LocksListRequestManufacturerSchlage
	LocksListRequestManufacturerSeam
	LocksListRequestManufacturerUnknown
	LocksListRequestManufacturerYale
	LocksListRequestManufacturerMinut
	LocksListRequestManufacturerTwoN
	LocksListRequestManufacturerTtlock
	LocksListRequestManufacturerNest
	LocksListRequestManufacturerIgloohome
	LocksListRequestManufacturerEcobee
	LocksListRequestManufacturerHubitat
)

func (l LocksListRequestManufacturer) String() string {
	switch l {
	default:
		return strconv.Itoa(int(l))
	case LocksListRequestManufacturerAkuvox:
		return "akuvox"
	case LocksListRequestManufacturerAugust:
		return "august"
	case LocksListRequestManufacturerBrivo:
		return "brivo"
	case LocksListRequestManufacturerButterflymx:
		return "butterflymx"
	case LocksListRequestManufacturerDoorking:
		return "doorking"
	case LocksListRequestManufacturerGenie:
		return "genie"
	case LocksListRequestManufacturerIgloo:
		return "igloo"
	case LocksListRequestManufacturerKeywe:
		return "keywe"
	case LocksListRequestManufacturerKwikset:
		return "kwikset"
	case LocksListRequestManufacturerLinear:
		return "linear"
	case LocksListRequestManufacturerLockly:
		return "lockly"
	case LocksListRequestManufacturerNuki:
		return "nuki"
	case LocksListRequestManufacturerPhilia:
		return "philia"
	case LocksListRequestManufacturerSalto:
		return "salto"
	case LocksListRequestManufacturerSamsung:
		return "samsung"
	case LocksListRequestManufacturerSchlage:
		return "schlage"
	case LocksListRequestManufacturerSeam:
		return "seam"
	case LocksListRequestManufacturerUnknown:
		return "unknown"
	case LocksListRequestManufacturerYale:
		return "yale"
	case LocksListRequestManufacturerMinut:
		return "minut"
	case LocksListRequestManufacturerTwoN:
		return "two_n"
	case LocksListRequestManufacturerTtlock:
		return "ttlock"
	case LocksListRequestManufacturerNest:
		return "nest"
	case LocksListRequestManufacturerIgloohome:
		return "igloohome"
	case LocksListRequestManufacturerEcobee:
		return "ecobee"
	case LocksListRequestManufacturerHubitat:
		return "hubitat"
	}
}

func (l LocksListRequestManufacturer) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", l.String())), nil
}

func (l *LocksListRequestManufacturer) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "akuvox":
		value := LocksListRequestManufacturerAkuvox
		*l = value
	case "august":
		value := LocksListRequestManufacturerAugust
		*l = value
	case "brivo":
		value := LocksListRequestManufacturerBrivo
		*l = value
	case "butterflymx":
		value := LocksListRequestManufacturerButterflymx
		*l = value
	case "doorking":
		value := LocksListRequestManufacturerDoorking
		*l = value
	case "genie":
		value := LocksListRequestManufacturerGenie
		*l = value
	case "igloo":
		value := LocksListRequestManufacturerIgloo
		*l = value
	case "keywe":
		value := LocksListRequestManufacturerKeywe
		*l = value
	case "kwikset":
		value := LocksListRequestManufacturerKwikset
		*l = value
	case "linear":
		value := LocksListRequestManufacturerLinear
		*l = value
	case "lockly":
		value := LocksListRequestManufacturerLockly
		*l = value
	case "nuki":
		value := LocksListRequestManufacturerNuki
		*l = value
	case "philia":
		value := LocksListRequestManufacturerPhilia
		*l = value
	case "salto":
		value := LocksListRequestManufacturerSalto
		*l = value
	case "samsung":
		value := LocksListRequestManufacturerSamsung
		*l = value
	case "schlage":
		value := LocksListRequestManufacturerSchlage
		*l = value
	case "seam":
		value := LocksListRequestManufacturerSeam
		*l = value
	case "unknown":
		value := LocksListRequestManufacturerUnknown
		*l = value
	case "yale":
		value := LocksListRequestManufacturerYale
		*l = value
	case "minut":
		value := LocksListRequestManufacturerMinut
		*l = value
	case "two_n":
		value := LocksListRequestManufacturerTwoN
		*l = value
	case "ttlock":
		value := LocksListRequestManufacturerTtlock
		*l = value
	case "nest":
		value := LocksListRequestManufacturerNest
		*l = value
	case "igloohome":
		value := LocksListRequestManufacturerIgloohome
		*l = value
	case "ecobee":
		value := LocksListRequestManufacturerEcobee
		*l = value
	case "hubitat":
		value := LocksListRequestManufacturerHubitat
		*l = value
	}
	return nil
}
