// This file was auto-generated by Fern from our API Definition.

package api

type LocksGetResponse struct {
	Lock   *any `json:"lock,omitempty"`
	Device *any `json:"device,omitempty"`
	Ok     bool `json:"ok"`
}
