// This file was auto-generated by Fern from our API Definition.

package api

type NoiseThresholdsListResponse struct {
	NoiseThresholds []*NoiseThreshold `json:"noise_thresholds,omitempty"`
	Ok              bool              `json:"ok"`
}
