// This file was auto-generated by Fern from our API Definition.

package api

type NoiseThresholdsCreateResponse struct {
	ActionAttempt *ActionAttempt `json:"action_attempt,omitempty"`
	Ok            bool           `json:"ok"`
}
