// This file was auto-generated by Fern from our API Definition.

package api

// ThermostatsHeatRequest is an in-lined request used by the Heat endpoint.
type ThermostatsHeatRequest struct {
	DeviceId                  string   `json:"device_id"`
	HeatingSetPointCelsius    *float64 `json:"heating_set_point_celsius,omitempty"`
	HeatingSetPointFahrenheit *float64 `json:"heating_set_point_fahrenheit,omitempty"`
	Sync                      *bool    `json:"sync,omitempty"`
}
