// This file was auto-generated by Fern from our API Definition.

package api

type UnmanagedGetResponse struct {
	AccessCode *UnmanagedGetResponseAccessCode `json:"access_code,omitempty"`
	Ok         bool                            `json:"ok"`
}
