// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

type UnmanagedListRequestDeviceType uint8

const (
	UnmanagedListRequestDeviceTypeAkuvoxLock UnmanagedListRequestDeviceType = iota + 1
	UnmanagedListRequestDeviceTypeAugustLock
	UnmanagedListRequestDeviceTypeBrivoAccessPoint
	UnmanagedListRequestDeviceTypeButterflymxPanel
	UnmanagedListRequestDeviceTypeDoorkingLock
	UnmanagedListRequestDeviceTypeGenieDoor
	UnmanagedListRequestDeviceTypeIglooLock
	UnmanagedListRequestDeviceTypeLinearLock
	UnmanagedListRequestDeviceTypeLocklyLock
	UnmanagedListRequestDeviceTypeKwiksetLock
	UnmanagedListRequestDeviceTypeNukiLock
	UnmanagedListRequestDeviceTypeSaltoLock
	UnmanagedListRequestDeviceTypeSchlageLock
	UnmanagedListRequestDeviceTypeSeamRelay
	UnmanagedListRequestDeviceTypeSmartthingsLock
	UnmanagedListRequestDeviceTypeYaleLock
	UnmanagedListRequestDeviceTypeTwoNIntercom
	UnmanagedListRequestDeviceTypeControlbywebDevice
	UnmanagedListRequestDeviceTypeTtlockLock
	UnmanagedListRequestDeviceTypeIgloohomeLock
	UnmanagedListRequestDeviceTypeHubitatLock
	UnmanagedListRequestDeviceTypeNoiseawareActivityZone
	UnmanagedListRequestDeviceTypeMinutSensor
	UnmanagedListRequestDeviceTypeEcobeeThermostat
	UnmanagedListRequestDeviceTypeNestThermostat
)

func (u UnmanagedListRequestDeviceType) String() string {
	switch u {
	default:
		return strconv.Itoa(int(u))
	case UnmanagedListRequestDeviceTypeAkuvoxLock:
		return "akuvox_lock"
	case UnmanagedListRequestDeviceTypeAugustLock:
		return "august_lock"
	case UnmanagedListRequestDeviceTypeBrivoAccessPoint:
		return "brivo_access_point"
	case UnmanagedListRequestDeviceTypeButterflymxPanel:
		return "butterflymx_panel"
	case UnmanagedListRequestDeviceTypeDoorkingLock:
		return "doorking_lock"
	case UnmanagedListRequestDeviceTypeGenieDoor:
		return "genie_door"
	case UnmanagedListRequestDeviceTypeIglooLock:
		return "igloo_lock"
	case UnmanagedListRequestDeviceTypeLinearLock:
		return "linear_lock"
	case UnmanagedListRequestDeviceTypeLocklyLock:
		return "lockly_lock"
	case UnmanagedListRequestDeviceTypeKwiksetLock:
		return "kwikset_lock"
	case UnmanagedListRequestDeviceTypeNukiLock:
		return "nuki_lock"
	case UnmanagedListRequestDeviceTypeSaltoLock:
		return "salto_lock"
	case UnmanagedListRequestDeviceTypeSchlageLock:
		return "schlage_lock"
	case UnmanagedListRequestDeviceTypeSeamRelay:
		return "seam_relay"
	case UnmanagedListRequestDeviceTypeSmartthingsLock:
		return "smartthings_lock"
	case UnmanagedListRequestDeviceTypeYaleLock:
		return "yale_lock"
	case UnmanagedListRequestDeviceTypeTwoNIntercom:
		return "two_n_intercom"
	case UnmanagedListRequestDeviceTypeControlbywebDevice:
		return "controlbyweb_device"
	case UnmanagedListRequestDeviceTypeTtlockLock:
		return "ttlock_lock"
	case UnmanagedListRequestDeviceTypeIgloohomeLock:
		return "igloohome_lock"
	case UnmanagedListRequestDeviceTypeHubitatLock:
		return "hubitat_lock"
	case UnmanagedListRequestDeviceTypeNoiseawareActivityZone:
		return "noiseaware_activity_zone"
	case UnmanagedListRequestDeviceTypeMinutSensor:
		return "minut_sensor"
	case UnmanagedListRequestDeviceTypeEcobeeThermostat:
		return "ecobee_thermostat"
	case UnmanagedListRequestDeviceTypeNestThermostat:
		return "nest_thermostat"
	}
}

func (u UnmanagedListRequestDeviceType) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", u.String())), nil
}

func (u *UnmanagedListRequestDeviceType) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "akuvox_lock":
		value := UnmanagedListRequestDeviceTypeAkuvoxLock
		*u = value
	case "august_lock":
		value := UnmanagedListRequestDeviceTypeAugustLock
		*u = value
	case "brivo_access_point":
		value := UnmanagedListRequestDeviceTypeBrivoAccessPoint
		*u = value
	case "butterflymx_panel":
		value := UnmanagedListRequestDeviceTypeButterflymxPanel
		*u = value
	case "doorking_lock":
		value := UnmanagedListRequestDeviceTypeDoorkingLock
		*u = value
	case "genie_door":
		value := UnmanagedListRequestDeviceTypeGenieDoor
		*u = value
	case "igloo_lock":
		value := UnmanagedListRequestDeviceTypeIglooLock
		*u = value
	case "linear_lock":
		value := UnmanagedListRequestDeviceTypeLinearLock
		*u = value
	case "lockly_lock":
		value := UnmanagedListRequestDeviceTypeLocklyLock
		*u = value
	case "kwikset_lock":
		value := UnmanagedListRequestDeviceTypeKwiksetLock
		*u = value
	case "nuki_lock":
		value := UnmanagedListRequestDeviceTypeNukiLock
		*u = value
	case "salto_lock":
		value := UnmanagedListRequestDeviceTypeSaltoLock
		*u = value
	case "schlage_lock":
		value := UnmanagedListRequestDeviceTypeSchlageLock
		*u = value
	case "seam_relay":
		value := UnmanagedListRequestDeviceTypeSeamRelay
		*u = value
	case "smartthings_lock":
		value := UnmanagedListRequestDeviceTypeSmartthingsLock
		*u = value
	case "yale_lock":
		value := UnmanagedListRequestDeviceTypeYaleLock
		*u = value
	case "two_n_intercom":
		value := UnmanagedListRequestDeviceTypeTwoNIntercom
		*u = value
	case "controlbyweb_device":
		value := UnmanagedListRequestDeviceTypeControlbywebDevice
		*u = value
	case "ttlock_lock":
		value := UnmanagedListRequestDeviceTypeTtlockLock
		*u = value
	case "igloohome_lock":
		value := UnmanagedListRequestDeviceTypeIgloohomeLock
		*u = value
	case "hubitat_lock":
		value := UnmanagedListRequestDeviceTypeHubitatLock
		*u = value
	case "noiseaware_activity_zone":
		value := UnmanagedListRequestDeviceTypeNoiseawareActivityZone
		*u = value
	case "minut_sensor":
		value := UnmanagedListRequestDeviceTypeMinutSensor
		*u = value
	case "ecobee_thermostat":
		value := UnmanagedListRequestDeviceTypeEcobeeThermostat
		*u = value
	case "nest_thermostat":
		value := UnmanagedListRequestDeviceTypeNestThermostat
		*u = value
	}
	return nil
}
