// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

type UnmanagedDeviceDeviceTypeUnmanagedDeviceDeviceType uint8

const (
	UnmanagedDeviceDeviceTypeUnmanagedDeviceDeviceTypeEcobeeThermostat UnmanagedDeviceDeviceTypeUnmanagedDeviceDeviceType = iota + 1
	UnmanagedDeviceDeviceTypeUnmanagedDeviceDeviceTypeNestThermostat
)

func (u UnmanagedDeviceDeviceTypeUnmanagedDeviceDeviceType) String() string {
	switch u {
	default:
		return strconv.Itoa(int(u))
	case UnmanagedDeviceDeviceTypeUnmanagedDeviceDeviceTypeEcobeeThermostat:
		return "ecobee_thermostat"
	case UnmanagedDeviceDeviceTypeUnmanagedDeviceDeviceTypeNestThermostat:
		return "nest_thermostat"
	}
}

func (u UnmanagedDeviceDeviceTypeUnmanagedDeviceDeviceType) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%q", u.String())), nil
}

func (u *UnmanagedDeviceDeviceTypeUnmanagedDeviceDeviceType) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "ecobee_thermostat":
		value := UnmanagedDeviceDeviceTypeUnmanagedDeviceDeviceTypeEcobeeThermostat
		*u = value
	case "nest_thermostat":
		value := UnmanagedDeviceDeviceTypeUnmanagedDeviceDeviceTypeNestThermostat
		*u = value
	}
	return nil
}
