// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/seamapi/go/internal"
)

type WebhooksCreateRequest struct {
	Url        string   `json:"url" url:"-"`
	EventTypes []string `json:"event_types,omitempty" url:"-"`
}

type WebhooksDeleteRequest struct {
	WebhookId string `json:"webhook_id" url:"-"`
}

type WebhooksGetRequest struct {
	WebhookId string `json:"webhook_id" url:"-"`
}

type Webhook struct {
	WebhookId  string   `json:"webhook_id" url:"webhook_id"`
	Url        string   `json:"url" url:"url"`
	EventTypes []string `json:"event_types,omitempty" url:"event_types,omitempty"`
	Secret     *string  `json:"secret,omitempty" url:"secret,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *Webhook) GetWebhookId() string {
	if w == nil {
		return ""
	}
	return w.WebhookId
}

func (w *Webhook) GetUrl() string {
	if w == nil {
		return ""
	}
	return w.Url
}

func (w *Webhook) GetEventTypes() []string {
	if w == nil {
		return nil
	}
	return w.EventTypes
}

func (w *Webhook) GetSecret() *string {
	if w == nil {
		return nil
	}
	return w.Secret
}

func (w *Webhook) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *Webhook) UnmarshalJSON(data []byte) error {
	type unmarshaler Webhook
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = Webhook(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *Webhook) String() string {
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WebhooksCreateResponse struct {
	Webhook *Webhook `json:"webhook,omitempty" url:"webhook,omitempty"`
	Ok      bool     `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhooksCreateResponse) GetWebhook() *Webhook {
	if w == nil {
		return nil
	}
	return w.Webhook
}

func (w *WebhooksCreateResponse) GetOk() bool {
	if w == nil {
		return false
	}
	return w.Ok
}

func (w *WebhooksCreateResponse) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WebhooksCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhooksCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WebhooksCreateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhooksCreateResponse) String() string {
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WebhooksDeleteResponse struct {
	Ok bool `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhooksDeleteResponse) GetOk() bool {
	if w == nil {
		return false
	}
	return w.Ok
}

func (w *WebhooksDeleteResponse) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WebhooksDeleteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhooksDeleteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WebhooksDeleteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhooksDeleteResponse) String() string {
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WebhooksGetResponse struct {
	Webhook *Webhook `json:"webhook,omitempty" url:"webhook,omitempty"`
	Ok      bool     `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhooksGetResponse) GetWebhook() *Webhook {
	if w == nil {
		return nil
	}
	return w.Webhook
}

func (w *WebhooksGetResponse) GetOk() bool {
	if w == nil {
		return false
	}
	return w.Ok
}

func (w *WebhooksGetResponse) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WebhooksGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhooksGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WebhooksGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhooksGetResponse) String() string {
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WebhooksListResponse struct {
	Webhooks []*Webhook `json:"webhooks,omitempty" url:"webhooks,omitempty"`
	Ok       bool       `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhooksListResponse) GetWebhooks() []*Webhook {
	if w == nil {
		return nil
	}
	return w.Webhooks
}

func (w *WebhooksListResponse) GetOk() bool {
	if w == nil {
		return false
	}
	return w.Ok
}

func (w *WebhooksListResponse) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WebhooksListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhooksListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WebhooksListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhooksListResponse) String() string {
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WebhooksUpdateResponse struct {
	Ok bool `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhooksUpdateResponse) GetOk() bool {
	if w == nil {
		return false
	}
	return w.Ok
}

func (w *WebhooksUpdateResponse) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WebhooksUpdateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhooksUpdateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WebhooksUpdateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhooksUpdateResponse) String() string {
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type WebhooksUpdateRequest struct {
	WebhookId  string   `json:"webhook_id" url:"-"`
	EventTypes []string `json:"event_types,omitempty" url:"-"`
}
