// This file was auto-generated by Fern from our API Definition.

package api

type WorkspacesListResponse struct {
	Workspaces []*Workspace `json:"workspaces,omitempty"`
	Ok         bool         `json:"ok"`
}
