// This file was auto-generated by Fern from our API Definition.

package acs

import (
	json "encoding/json"
	fmt "fmt"
	seamapigo "github.com/seamapi/go"
	core "github.com/seamapi/go/core"
)

type CredentialProvisioningAutomationsLaunchRequest struct {
	UserIdentityId               string  `json:"user_identity_id" url:"user_identity_id"`
	CredentialManagerAcsSystemId string  `json:"credential_manager_acs_system_id" url:"credential_manager_acs_system_id"`
	AcsCredentialPoolId          *string `json:"acs_credential_pool_id,omitempty" url:"acs_credential_pool_id,omitempty"`
	CreateCredentialManagerUser  *bool   `json:"create_credential_manager_user,omitempty" url:"create_credential_manager_user,omitempty"`
	CredentialManagerAcsUserId   *string `json:"credential_manager_acs_user_id,omitempty" url:"credential_manager_acs_user_id,omitempty"`
}

type CredentialProvisioningAutomationsLaunchResponse struct {
	AcsCredentialProvisioningAutomation *seamapigo.AcsCredentialProvisioningAutomation `json:"acs_credential_provisioning_automation,omitempty" url:"acs_credential_provisioning_automation,omitempty"`
	Ok                                  bool                                           `json:"ok" url:"ok"`

	_rawJSON json.RawMessage
}

func (c *CredentialProvisioningAutomationsLaunchResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CredentialProvisioningAutomationsLaunchResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CredentialProvisioningAutomationsLaunchResponse(value)
	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CredentialProvisioningAutomationsLaunchResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
