// This file was auto-generated by Fern from our API Definition.

package acs

import (
	json "encoding/json"
	fmt "fmt"
	seamapigo "github.com/seamapi/go"
	internal "github.com/seamapi/go/internal"
	time "time"
)

type UsersAddToAccessGroupRequest struct {
	AcsUserId        string `json:"acs_user_id" url:"-"`
	AcsAccessGroupId string `json:"acs_access_group_id" url:"-"`
}

type UsersCreateRequest struct {
	AcsSystemId       string                            `json:"acs_system_id" url:"-"`
	AcsAccessGroupIds []string                          `json:"acs_access_group_ids,omitempty" url:"-"`
	UserIdentityId    *string                           `json:"user_identity_id,omitempty" url:"-"`
	AccessSchedule    *UsersCreateRequestAccessSchedule `json:"access_schedule,omitempty" url:"-"`
	FullName          *string                           `json:"full_name,omitempty" url:"-"`
	Email             *string                           `json:"email,omitempty" url:"-"`
	PhoneNumber       *string                           `json:"phone_number,omitempty" url:"-"`
	EmailAddress      *string                           `json:"email_address,omitempty" url:"-"`
}

type UsersDeleteRequest struct {
	AcsUserId string `json:"acs_user_id" url:"-"`
}

type UsersGetRequest struct {
	AcsUserId string `json:"acs_user_id" url:"-"`
}

type UsersListRequest struct {
	UserIdentityId           *string `json:"user_identity_id,omitempty" url:"-"`
	UserIdentityPhoneNumber  *string `json:"user_identity_phone_number,omitempty" url:"-"`
	UserIdentityEmailAddress *string `json:"user_identity_email_address,omitempty" url:"-"`
	AcsSystemId              *string `json:"acs_system_id,omitempty" url:"-"`
}

type UsersListAccessibleEntrancesRequest struct {
	AcsUserId string `json:"acs_user_id" url:"-"`
}

type UsersRemoveFromAccessGroupRequest struct {
	AcsUserId        string `json:"acs_user_id" url:"-"`
	AcsAccessGroupId string `json:"acs_access_group_id" url:"-"`
}

type UsersRevokeAccessToAllEntrancesRequest struct {
	AcsUserId string `json:"acs_user_id" url:"-"`
}

type UsersSuspendRequest struct {
	AcsUserId string `json:"acs_user_id" url:"-"`
}

type UsersAddToAccessGroupResponse struct {
	Ok bool `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UsersAddToAccessGroupResponse) GetOk() bool {
	if u == nil {
		return false
	}
	return u.Ok
}

func (u *UsersAddToAccessGroupResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UsersAddToAccessGroupResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UsersAddToAccessGroupResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UsersAddToAccessGroupResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UsersAddToAccessGroupResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UsersCreateRequestAccessSchedule struct {
	StartsAt time.Time `json:"starts_at" url:"starts_at"`
	EndsAt   time.Time `json:"ends_at" url:"ends_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UsersCreateRequestAccessSchedule) GetStartsAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.StartsAt
}

func (u *UsersCreateRequestAccessSchedule) GetEndsAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.EndsAt
}

func (u *UsersCreateRequestAccessSchedule) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UsersCreateRequestAccessSchedule) UnmarshalJSON(data []byte) error {
	type embed UsersCreateRequestAccessSchedule
	var unmarshaler = struct {
		embed
		StartsAt *internal.DateTime `json:"starts_at"`
		EndsAt   *internal.DateTime `json:"ends_at"`
	}{
		embed: embed(*u),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*u = UsersCreateRequestAccessSchedule(unmarshaler.embed)
	u.StartsAt = unmarshaler.StartsAt.Time()
	u.EndsAt = unmarshaler.EndsAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UsersCreateRequestAccessSchedule) MarshalJSON() ([]byte, error) {
	type embed UsersCreateRequestAccessSchedule
	var marshaler = struct {
		embed
		StartsAt *internal.DateTime `json:"starts_at"`
		EndsAt   *internal.DateTime `json:"ends_at"`
	}{
		embed:    embed(*u),
		StartsAt: internal.NewDateTime(u.StartsAt),
		EndsAt:   internal.NewDateTime(u.EndsAt),
	}
	return json.Marshal(marshaler)
}

func (u *UsersCreateRequestAccessSchedule) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UsersCreateResponse struct {
	AcsUser *seamapigo.AcsUser `json:"acs_user,omitempty" url:"acs_user,omitempty"`
	Ok      bool               `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UsersCreateResponse) GetAcsUser() *seamapigo.AcsUser {
	if u == nil {
		return nil
	}
	return u.AcsUser
}

func (u *UsersCreateResponse) GetOk() bool {
	if u == nil {
		return false
	}
	return u.Ok
}

func (u *UsersCreateResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UsersCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UsersCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UsersCreateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UsersCreateResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UsersDeleteResponse struct {
	Ok bool `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UsersDeleteResponse) GetOk() bool {
	if u == nil {
		return false
	}
	return u.Ok
}

func (u *UsersDeleteResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UsersDeleteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UsersDeleteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UsersDeleteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UsersDeleteResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UsersGetResponse struct {
	AcsUser *seamapigo.AcsUser `json:"acs_user,omitempty" url:"acs_user,omitempty"`
	Ok      bool               `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UsersGetResponse) GetAcsUser() *seamapigo.AcsUser {
	if u == nil {
		return nil
	}
	return u.AcsUser
}

func (u *UsersGetResponse) GetOk() bool {
	if u == nil {
		return false
	}
	return u.Ok
}

func (u *UsersGetResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UsersGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UsersGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UsersGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UsersGetResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UsersListAccessibleEntrancesResponse struct {
	AcsEntrances []*seamapigo.AcsEntrance `json:"acs_entrances,omitempty" url:"acs_entrances,omitempty"`
	Ok           bool                     `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UsersListAccessibleEntrancesResponse) GetAcsEntrances() []*seamapigo.AcsEntrance {
	if u == nil {
		return nil
	}
	return u.AcsEntrances
}

func (u *UsersListAccessibleEntrancesResponse) GetOk() bool {
	if u == nil {
		return false
	}
	return u.Ok
}

func (u *UsersListAccessibleEntrancesResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UsersListAccessibleEntrancesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UsersListAccessibleEntrancesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UsersListAccessibleEntrancesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UsersListAccessibleEntrancesResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UsersListResponse struct {
	AcsUsers []*seamapigo.AcsUser `json:"acs_users,omitempty" url:"acs_users,omitempty"`
	Ok       bool                 `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UsersListResponse) GetAcsUsers() []*seamapigo.AcsUser {
	if u == nil {
		return nil
	}
	return u.AcsUsers
}

func (u *UsersListResponse) GetOk() bool {
	if u == nil {
		return false
	}
	return u.Ok
}

func (u *UsersListResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UsersListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UsersListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UsersListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UsersListResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UsersRemoveFromAccessGroupResponse struct {
	Ok bool `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UsersRemoveFromAccessGroupResponse) GetOk() bool {
	if u == nil {
		return false
	}
	return u.Ok
}

func (u *UsersRemoveFromAccessGroupResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UsersRemoveFromAccessGroupResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UsersRemoveFromAccessGroupResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UsersRemoveFromAccessGroupResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UsersRemoveFromAccessGroupResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UsersRevokeAccessToAllEntrancesResponse struct {
	Ok bool `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UsersRevokeAccessToAllEntrancesResponse) GetOk() bool {
	if u == nil {
		return false
	}
	return u.Ok
}

func (u *UsersRevokeAccessToAllEntrancesResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UsersRevokeAccessToAllEntrancesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UsersRevokeAccessToAllEntrancesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UsersRevokeAccessToAllEntrancesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UsersRevokeAccessToAllEntrancesResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UsersSuspendResponse struct {
	Ok bool `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UsersSuspendResponse) GetOk() bool {
	if u == nil {
		return false
	}
	return u.Ok
}

func (u *UsersSuspendResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UsersSuspendResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UsersSuspendResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UsersSuspendResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UsersSuspendResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UsersUnsuspendResponse struct {
	Ok bool `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UsersUnsuspendResponse) GetOk() bool {
	if u == nil {
		return false
	}
	return u.Ok
}

func (u *UsersUnsuspendResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UsersUnsuspendResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UsersUnsuspendResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UsersUnsuspendResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UsersUnsuspendResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UsersUpdateRequestAccessSchedule struct {
	StartsAt time.Time `json:"starts_at" url:"starts_at"`
	EndsAt   time.Time `json:"ends_at" url:"ends_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UsersUpdateRequestAccessSchedule) GetStartsAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.StartsAt
}

func (u *UsersUpdateRequestAccessSchedule) GetEndsAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.EndsAt
}

func (u *UsersUpdateRequestAccessSchedule) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UsersUpdateRequestAccessSchedule) UnmarshalJSON(data []byte) error {
	type embed UsersUpdateRequestAccessSchedule
	var unmarshaler = struct {
		embed
		StartsAt *internal.DateTime `json:"starts_at"`
		EndsAt   *internal.DateTime `json:"ends_at"`
	}{
		embed: embed(*u),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*u = UsersUpdateRequestAccessSchedule(unmarshaler.embed)
	u.StartsAt = unmarshaler.StartsAt.Time()
	u.EndsAt = unmarshaler.EndsAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UsersUpdateRequestAccessSchedule) MarshalJSON() ([]byte, error) {
	type embed UsersUpdateRequestAccessSchedule
	var marshaler = struct {
		embed
		StartsAt *internal.DateTime `json:"starts_at"`
		EndsAt   *internal.DateTime `json:"ends_at"`
	}{
		embed:    embed(*u),
		StartsAt: internal.NewDateTime(u.StartsAt),
		EndsAt:   internal.NewDateTime(u.EndsAt),
	}
	return json.Marshal(marshaler)
}

func (u *UsersUpdateRequestAccessSchedule) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UsersUpdateResponse struct {
	Ok bool `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UsersUpdateResponse) GetOk() bool {
	if u == nil {
		return false
	}
	return u.Ok
}

func (u *UsersUpdateResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UsersUpdateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UsersUpdateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UsersUpdateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UsersUpdateResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UsersUnsuspendRequest struct {
	AcsUserId string `json:"acs_user_id" url:"-"`
}

type UsersUpdateRequest struct {
	AccessSchedule *UsersUpdateRequestAccessSchedule `json:"access_schedule,omitempty" url:"-"`
	AcsUserId      string                            `json:"acs_user_id" url:"-"`
	FullName       *string                           `json:"full_name,omitempty" url:"-"`
	Email          *string                           `json:"email,omitempty" url:"-"`
	PhoneNumber    *string                           `json:"phone_number,omitempty" url:"-"`
	EmailAddress   *string                           `json:"email_address,omitempty" url:"-"`
	HidAcsSystemId *string                           `json:"hid_acs_system_id,omitempty" url:"-"`
}
