// This file was auto-generated by Fern from our API Definition.

package noisesensors

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	errors "errors"
	seamapigo "github.com/seamapi/go"
	core "github.com/seamapi/go/core"
	io "io"
	http "net/http"
)

type SimulateClient interface {
	TriggerNoiseThreshold(ctx context.Context, request *NoiseSensorsSimulateTriggerNoiseThresholdRequest) (*seamapigo.NoiseSensorsSimulateTriggerNoiseThresholdResponse, error)
}

func NewSimulateClient(opts ...core.ClientOption) SimulateClient {
	options := core.NewClientOptions()
	for _, opt := range opts {
		opt(options)
	}
	return &simulateClient{
		baseURL:    options.BaseURL,
		httpClient: options.HTTPClient,
		header:     options.ToHeader(),
	}
}

type simulateClient struct {
	baseURL    string
	httpClient core.HTTPClient
	header     http.Header
}

func (s *simulateClient) TriggerNoiseThreshold(ctx context.Context, request *NoiseSensorsSimulateTriggerNoiseThresholdRequest) (*seamapigo.NoiseSensorsSimulateTriggerNoiseThresholdResponse, error) {
	baseURL := "https://connect.getseam.com"
	if s.baseURL != "" {
		baseURL = s.baseURL
	}
	endpointURL := baseURL + "/" + "noise_sensors/simulate/trigger_noise_threshold"

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 400:
			value := new(BadRequestError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		case 401:
			value := new(UnauthorizedError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		}
		return apiError
	}

	var response *seamapigo.NoiseSensorsSimulateTriggerNoiseThresholdResponse
	if err := core.DoRequest(
		ctx,
		s.httpClient,
		endpointURL,
		http.MethodPost,
		request,
		&response,
		false,
		s.header,
		errorDecoder,
	); err != nil {
		return response, err
	}
	return response, nil
}
