// This file was auto-generated by Fern from our API Definition.

package thermostats

import (
	json "encoding/json"
	fmt "fmt"
	seamapigo "github.com/seamapi/go"
	internal "github.com/seamapi/go/internal"
)

type ClimateSettingSchedulesCreateRequest struct {
	ScheduleType              *string                                              `json:"schedule_type,omitempty" url:"-"`
	DeviceId                  string                                               `json:"device_id" url:"-"`
	Name                      *string                                              `json:"name,omitempty" url:"-"`
	ScheduleStartsAt          string                                               `json:"schedule_starts_at" url:"-"`
	ScheduleEndsAt            string                                               `json:"schedule_ends_at" url:"-"`
	AutomaticHeatingEnabled   *bool                                                `json:"automatic_heating_enabled,omitempty" url:"-"`
	AutomaticCoolingEnabled   *bool                                                `json:"automatic_cooling_enabled,omitempty" url:"-"`
	HvacModeSetting           *ClimateSettingSchedulesCreateRequestHvacModeSetting `json:"hvac_mode_setting,omitempty" url:"-"`
	CoolingSetPointCelsius    *float64                                             `json:"cooling_set_point_celsius,omitempty" url:"-"`
	HeatingSetPointCelsius    *float64                                             `json:"heating_set_point_celsius,omitempty" url:"-"`
	CoolingSetPointFahrenheit *float64                                             `json:"cooling_set_point_fahrenheit,omitempty" url:"-"`
	HeatingSetPointFahrenheit *float64                                             `json:"heating_set_point_fahrenheit,omitempty" url:"-"`
	ManualOverrideAllowed     *bool                                                `json:"manual_override_allowed,omitempty" url:"-"`
}

type ClimateSettingSchedulesDeleteRequest struct {
	ClimateSettingScheduleId string `json:"climate_setting_schedule_id" url:"-"`
}

type ClimateSettingSchedulesGetRequest struct {
	ClimateSettingScheduleId *string `json:"climate_setting_schedule_id,omitempty" url:"-"`
	DeviceId                 *string `json:"device_id,omitempty" url:"-"`
}

type ClimateSettingSchedulesListRequest struct {
	DeviceId          string  `json:"device_id" url:"-"`
	UserIdentifierKey *string `json:"user_identifier_key,omitempty" url:"-"`
}

type ClimateSettingSchedulesCreateRequestHvacModeSetting string

const (
	ClimateSettingSchedulesCreateRequestHvacModeSettingOff      ClimateSettingSchedulesCreateRequestHvacModeSetting = "off"
	ClimateSettingSchedulesCreateRequestHvacModeSettingHeat     ClimateSettingSchedulesCreateRequestHvacModeSetting = "heat"
	ClimateSettingSchedulesCreateRequestHvacModeSettingCool     ClimateSettingSchedulesCreateRequestHvacModeSetting = "cool"
	ClimateSettingSchedulesCreateRequestHvacModeSettingHeatCool ClimateSettingSchedulesCreateRequestHvacModeSetting = "heat_cool"
)

func NewClimateSettingSchedulesCreateRequestHvacModeSettingFromString(s string) (ClimateSettingSchedulesCreateRequestHvacModeSetting, error) {
	switch s {
	case "off":
		return ClimateSettingSchedulesCreateRequestHvacModeSettingOff, nil
	case "heat":
		return ClimateSettingSchedulesCreateRequestHvacModeSettingHeat, nil
	case "cool":
		return ClimateSettingSchedulesCreateRequestHvacModeSettingCool, nil
	case "heat_cool":
		return ClimateSettingSchedulesCreateRequestHvacModeSettingHeatCool, nil
	}
	var t ClimateSettingSchedulesCreateRequestHvacModeSetting
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ClimateSettingSchedulesCreateRequestHvacModeSetting) Ptr() *ClimateSettingSchedulesCreateRequestHvacModeSetting {
	return &c
}

type ClimateSettingSchedulesCreateResponse struct {
	ClimateSettingSchedule *seamapigo.ClimateSettingSchedule `json:"climate_setting_schedule,omitempty" url:"climate_setting_schedule,omitempty"`
	Ok                     bool                              `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ClimateSettingSchedulesCreateResponse) GetClimateSettingSchedule() *seamapigo.ClimateSettingSchedule {
	if c == nil {
		return nil
	}
	return c.ClimateSettingSchedule
}

func (c *ClimateSettingSchedulesCreateResponse) GetOk() bool {
	if c == nil {
		return false
	}
	return c.Ok
}

func (c *ClimateSettingSchedulesCreateResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ClimateSettingSchedulesCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ClimateSettingSchedulesCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ClimateSettingSchedulesCreateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ClimateSettingSchedulesCreateResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ClimateSettingSchedulesDeleteResponse struct {
	Ok bool `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ClimateSettingSchedulesDeleteResponse) GetOk() bool {
	if c == nil {
		return false
	}
	return c.Ok
}

func (c *ClimateSettingSchedulesDeleteResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ClimateSettingSchedulesDeleteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ClimateSettingSchedulesDeleteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ClimateSettingSchedulesDeleteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ClimateSettingSchedulesDeleteResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ClimateSettingSchedulesGetResponse struct {
	ClimateSettingSchedule *seamapigo.ClimateSettingSchedule `json:"climate_setting_schedule,omitempty" url:"climate_setting_schedule,omitempty"`
	Ok                     bool                              `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ClimateSettingSchedulesGetResponse) GetClimateSettingSchedule() *seamapigo.ClimateSettingSchedule {
	if c == nil {
		return nil
	}
	return c.ClimateSettingSchedule
}

func (c *ClimateSettingSchedulesGetResponse) GetOk() bool {
	if c == nil {
		return false
	}
	return c.Ok
}

func (c *ClimateSettingSchedulesGetResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ClimateSettingSchedulesGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ClimateSettingSchedulesGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ClimateSettingSchedulesGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ClimateSettingSchedulesGetResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ClimateSettingSchedulesListResponse struct {
	ClimateSettingSchedules []*seamapigo.ClimateSettingSchedule `json:"climate_setting_schedules,omitempty" url:"climate_setting_schedules,omitempty"`
	Ok                      bool                                `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ClimateSettingSchedulesListResponse) GetClimateSettingSchedules() []*seamapigo.ClimateSettingSchedule {
	if c == nil {
		return nil
	}
	return c.ClimateSettingSchedules
}

func (c *ClimateSettingSchedulesListResponse) GetOk() bool {
	if c == nil {
		return false
	}
	return c.Ok
}

func (c *ClimateSettingSchedulesListResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ClimateSettingSchedulesListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ClimateSettingSchedulesListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ClimateSettingSchedulesListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ClimateSettingSchedulesListResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ClimateSettingSchedulesUpdateRequestHvacModeSetting string

const (
	ClimateSettingSchedulesUpdateRequestHvacModeSettingOff      ClimateSettingSchedulesUpdateRequestHvacModeSetting = "off"
	ClimateSettingSchedulesUpdateRequestHvacModeSettingHeat     ClimateSettingSchedulesUpdateRequestHvacModeSetting = "heat"
	ClimateSettingSchedulesUpdateRequestHvacModeSettingCool     ClimateSettingSchedulesUpdateRequestHvacModeSetting = "cool"
	ClimateSettingSchedulesUpdateRequestHvacModeSettingHeatCool ClimateSettingSchedulesUpdateRequestHvacModeSetting = "heat_cool"
)

func NewClimateSettingSchedulesUpdateRequestHvacModeSettingFromString(s string) (ClimateSettingSchedulesUpdateRequestHvacModeSetting, error) {
	switch s {
	case "off":
		return ClimateSettingSchedulesUpdateRequestHvacModeSettingOff, nil
	case "heat":
		return ClimateSettingSchedulesUpdateRequestHvacModeSettingHeat, nil
	case "cool":
		return ClimateSettingSchedulesUpdateRequestHvacModeSettingCool, nil
	case "heat_cool":
		return ClimateSettingSchedulesUpdateRequestHvacModeSettingHeatCool, nil
	}
	var t ClimateSettingSchedulesUpdateRequestHvacModeSetting
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ClimateSettingSchedulesUpdateRequestHvacModeSetting) Ptr() *ClimateSettingSchedulesUpdateRequestHvacModeSetting {
	return &c
}

type ClimateSettingSchedulesUpdateResponse struct {
	ClimateSettingSchedule *seamapigo.ClimateSettingSchedule `json:"climate_setting_schedule,omitempty" url:"climate_setting_schedule,omitempty"`
	Ok                     bool                              `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ClimateSettingSchedulesUpdateResponse) GetClimateSettingSchedule() *seamapigo.ClimateSettingSchedule {
	if c == nil {
		return nil
	}
	return c.ClimateSettingSchedule
}

func (c *ClimateSettingSchedulesUpdateResponse) GetOk() bool {
	if c == nil {
		return false
	}
	return c.Ok
}

func (c *ClimateSettingSchedulesUpdateResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ClimateSettingSchedulesUpdateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ClimateSettingSchedulesUpdateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ClimateSettingSchedulesUpdateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ClimateSettingSchedulesUpdateResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ClimateSettingSchedulesUpdateRequest struct {
	ClimateSettingScheduleId  string                                               `json:"climate_setting_schedule_id" url:"-"`
	ScheduleType              *string                                              `json:"schedule_type,omitempty" url:"-"`
	Name                      *string                                              `json:"name,omitempty" url:"-"`
	ScheduleStartsAt          *string                                              `json:"schedule_starts_at,omitempty" url:"-"`
	ScheduleEndsAt            *string                                              `json:"schedule_ends_at,omitempty" url:"-"`
	AutomaticHeatingEnabled   *bool                                                `json:"automatic_heating_enabled,omitempty" url:"-"`
	AutomaticCoolingEnabled   *bool                                                `json:"automatic_cooling_enabled,omitempty" url:"-"`
	HvacModeSetting           *ClimateSettingSchedulesUpdateRequestHvacModeSetting `json:"hvac_mode_setting,omitempty" url:"-"`
	CoolingSetPointCelsius    *float64                                             `json:"cooling_set_point_celsius,omitempty" url:"-"`
	HeatingSetPointCelsius    *float64                                             `json:"heating_set_point_celsius,omitempty" url:"-"`
	CoolingSetPointFahrenheit *float64                                             `json:"cooling_set_point_fahrenheit,omitempty" url:"-"`
	HeatingSetPointFahrenheit *float64                                             `json:"heating_set_point_fahrenheit,omitempty" url:"-"`
	ManualOverrideAllowed     *bool                                                `json:"manual_override_allowed,omitempty" url:"-"`
}
