// This file was auto-generated by Fern from our API Definition.

package thermostats

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	errors "errors"
	seamapigo "github.com/seamapi/go"
	core "github.com/seamapi/go/core"
	io "io"
	http "net/http"
)

type ClimateSettingSchedulesClient interface {
	Create(ctx context.Context, request *ThermostatsClimateSettingSchedulesCreateRequest) (*seamapigo.ThermostatsClimateSettingSchedulesCreateResponse, error)
	Delete(ctx context.Context, request *ThermostatsClimateSettingSchedulesDeleteRequest) (*seamapigo.ThermostatsClimateSettingSchedulesDeleteResponse, error)
	Get(ctx context.Context, request *ThermostatsClimateSettingSchedulesGetRequest) (*seamapigo.ThermostatsClimateSettingSchedulesGetResponse, error)
	List(ctx context.Context, request *ThermostatsClimateSettingSchedulesListRequest) (*seamapigo.ThermostatsClimateSettingSchedulesListResponse, error)
	Update(ctx context.Context, request *ThermostatsClimateSettingSchedulesUpdateRequest) (*seamapigo.ThermostatsClimateSettingSchedulesUpdateResponse, error)
}

func NewClimateSettingSchedulesClient(opts ...core.ClientOption) ClimateSettingSchedulesClient {
	options := core.NewClientOptions()
	for _, opt := range opts {
		opt(options)
	}
	return &climateSettingSchedulesClient{
		baseURL:    options.BaseURL,
		httpClient: options.HTTPClient,
		header:     options.ToHeader(),
	}
}

type climateSettingSchedulesClient struct {
	baseURL    string
	httpClient core.HTTPClient
	header     http.Header
}

func (c *climateSettingSchedulesClient) Create(ctx context.Context, request *ThermostatsClimateSettingSchedulesCreateRequest) (*seamapigo.ThermostatsClimateSettingSchedulesCreateResponse, error) {
	baseURL := "https://connect.getseam.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	endpointURL := baseURL + "/" + "thermostats/climate_setting_schedules/create"

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 400:
			value := new(BadRequestError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		case 401:
			value := new(UnauthorizedError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		}
		return apiError
	}

	var response *seamapigo.ThermostatsClimateSettingSchedulesCreateResponse
	if err := core.DoRequest(
		ctx,
		c.httpClient,
		endpointURL,
		http.MethodPost,
		request,
		&response,
		false,
		c.header,
		errorDecoder,
	); err != nil {
		return response, err
	}
	return response, nil
}

func (c *climateSettingSchedulesClient) Delete(ctx context.Context, request *ThermostatsClimateSettingSchedulesDeleteRequest) (*seamapigo.ThermostatsClimateSettingSchedulesDeleteResponse, error) {
	baseURL := "https://connect.getseam.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	endpointURL := baseURL + "/" + "thermostats/climate_setting_schedules/delete"

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 400:
			value := new(BadRequestError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		case 401:
			value := new(UnauthorizedError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		}
		return apiError
	}

	var response *seamapigo.ThermostatsClimateSettingSchedulesDeleteResponse
	if err := core.DoRequest(
		ctx,
		c.httpClient,
		endpointURL,
		http.MethodPost,
		request,
		&response,
		false,
		c.header,
		errorDecoder,
	); err != nil {
		return response, err
	}
	return response, nil
}

func (c *climateSettingSchedulesClient) Get(ctx context.Context, request *ThermostatsClimateSettingSchedulesGetRequest) (*seamapigo.ThermostatsClimateSettingSchedulesGetResponse, error) {
	baseURL := "https://connect.getseam.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	endpointURL := baseURL + "/" + "thermostats/climate_setting_schedules/get"

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 400:
			value := new(BadRequestError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		case 401:
			value := new(UnauthorizedError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		}
		return apiError
	}

	var response *seamapigo.ThermostatsClimateSettingSchedulesGetResponse
	if err := core.DoRequest(
		ctx,
		c.httpClient,
		endpointURL,
		http.MethodPost,
		request,
		&response,
		false,
		c.header,
		errorDecoder,
	); err != nil {
		return response, err
	}
	return response, nil
}

func (c *climateSettingSchedulesClient) List(ctx context.Context, request *ThermostatsClimateSettingSchedulesListRequest) (*seamapigo.ThermostatsClimateSettingSchedulesListResponse, error) {
	baseURL := "https://connect.getseam.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	endpointURL := baseURL + "/" + "thermostats/climate_setting_schedules/list"

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 400:
			value := new(BadRequestError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		case 401:
			value := new(UnauthorizedError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		}
		return apiError
	}

	var response *seamapigo.ThermostatsClimateSettingSchedulesListResponse
	if err := core.DoRequest(
		ctx,
		c.httpClient,
		endpointURL,
		http.MethodPost,
		request,
		&response,
		false,
		c.header,
		errorDecoder,
	); err != nil {
		return response, err
	}
	return response, nil
}

func (c *climateSettingSchedulesClient) Update(ctx context.Context, request *ThermostatsClimateSettingSchedulesUpdateRequest) (*seamapigo.ThermostatsClimateSettingSchedulesUpdateResponse, error) {
	baseURL := "https://connect.getseam.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	endpointURL := baseURL + "/" + "thermostats/climate_setting_schedules/update"

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 400:
			value := new(BadRequestError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		case 401:
			value := new(UnauthorizedError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		}
		return apiError
	}

	var response *seamapigo.ThermostatsClimateSettingSchedulesUpdateResponse
	if err := core.DoRequest(
		ctx,
		c.httpClient,
		endpointURL,
		http.MethodPost,
		request,
		&response,
		false,
		c.header,
		errorDecoder,
	); err != nil {
		return response, err
	}
	return response, nil
}
