// This file was auto-generated by Fern from our API Definition.

package thermostats

// ThermostatsClimateSettingSchedulesDeleteRequest is an in-lined request used by the Delete endpoint.
type ThermostatsClimateSettingSchedulesDeleteRequest struct {
	ClimateSettingScheduleId string `json:"climate_setting_schedule_id"`
}
