// This file was auto-generated by Fern from our API Definition.

package accesscodes

// AccessCodesUnmanagedDeleteRequest is an in-lined request used by the Delete endpoint.
type AccessCodesUnmanagedDeleteRequest struct {
	AccessCodeId string `json:"access_code_id"`
	Sync         *bool  `json:"sync,omitempty"`
}
