// This file was auto-generated by Fern from our API Definition.

package accesscodes

// SimulateCreateUnmanagedAccessCodeRequest is an in-lined request used by the CreateUnmanagedAccessCode endpoint.
type SimulateCreateUnmanagedAccessCodeRequest struct {
	DeviceId string `json:"device_id"`
	Name     string `json:"name"`
	Code     string `json:"code"`
}
