// This file was auto-generated by Fern from our API Definition.

package accesscodes

import (
	json "encoding/json"
	fmt "fmt"
	seamapigo "github.com/seamapi/go"
	internal "github.com/seamapi/go/internal"
)

type UnmanagedConvertToManagedRequest struct {
	AccessCodeId                  string `json:"access_code_id" url:"-"`
	IsExternalModificationAllowed *bool  `json:"is_external_modification_allowed,omitempty" url:"-"`
	AllowExternalModification     *bool  `json:"allow_external_modification,omitempty" url:"-"`
	Force                         *bool  `json:"force,omitempty" url:"-"`
	Sync                          *bool  `json:"sync,omitempty" url:"-"`
}

type UnmanagedDeleteRequest struct {
	AccessCodeId string `json:"access_code_id" url:"-"`
	Sync         *bool  `json:"sync,omitempty" url:"-"`
}

type UnmanagedGetRequest struct {
	DeviceId     *string `json:"device_id,omitempty" url:"-"`
	AccessCodeId *string `json:"access_code_id,omitempty" url:"-"`
	Code         *string `json:"code,omitempty" url:"-"`
}

type UnmanagedListRequest struct {
	DeviceId          string  `json:"device_id" url:"-"`
	UserIdentifierKey *string `json:"user_identifier_key,omitempty" url:"-"`
}

type UnmanagedConvertToManagedResponse struct {
	Ok bool `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnmanagedConvertToManagedResponse) GetOk() bool {
	if u == nil {
		return false
	}
	return u.Ok
}

func (u *UnmanagedConvertToManagedResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UnmanagedConvertToManagedResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UnmanagedConvertToManagedResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnmanagedConvertToManagedResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnmanagedConvertToManagedResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UnmanagedDeleteResponse struct {
	ActionAttempt *seamapigo.ActionAttempt `json:"action_attempt,omitempty" url:"action_attempt,omitempty"`
	Ok            bool                     `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnmanagedDeleteResponse) GetActionAttempt() *seamapigo.ActionAttempt {
	if u == nil {
		return nil
	}
	return u.ActionAttempt
}

func (u *UnmanagedDeleteResponse) GetOk() bool {
	if u == nil {
		return false
	}
	return u.Ok
}

func (u *UnmanagedDeleteResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UnmanagedDeleteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UnmanagedDeleteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnmanagedDeleteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnmanagedDeleteResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UnmanagedGetResponse struct {
	AccessCode *seamapigo.UnmanagedAccessCode `json:"access_code,omitempty" url:"access_code,omitempty"`
	Ok         bool                           `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnmanagedGetResponse) GetAccessCode() *seamapigo.UnmanagedAccessCode {
	if u == nil {
		return nil
	}
	return u.AccessCode
}

func (u *UnmanagedGetResponse) GetOk() bool {
	if u == nil {
		return false
	}
	return u.Ok
}

func (u *UnmanagedGetResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UnmanagedGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UnmanagedGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnmanagedGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnmanagedGetResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UnmanagedListResponse struct {
	AccessCodes []*seamapigo.UnmanagedAccessCode `json:"access_codes,omitempty" url:"access_codes,omitempty"`
	Ok          bool                             `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnmanagedListResponse) GetAccessCodes() []*seamapigo.UnmanagedAccessCode {
	if u == nil {
		return nil
	}
	return u.AccessCodes
}

func (u *UnmanagedListResponse) GetOk() bool {
	if u == nil {
		return false
	}
	return u.Ok
}

func (u *UnmanagedListResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UnmanagedListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UnmanagedListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnmanagedListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnmanagedListResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UnmanagedUpdateResponse struct {
	Ok bool `json:"ok" url:"ok"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnmanagedUpdateResponse) GetOk() bool {
	if u == nil {
		return false
	}
	return u.Ok
}

func (u *UnmanagedUpdateResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UnmanagedUpdateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UnmanagedUpdateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnmanagedUpdateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnmanagedUpdateResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UnmanagedUpdateRequest struct {
	AccessCodeId                  string `json:"access_code_id" url:"-"`
	IsManaged                     bool   `json:"is_managed" url:"-"`
	AllowExternalModification     *bool  `json:"allow_external_modification,omitempty" url:"-"`
	IsExternalModificationAllowed *bool  `json:"is_external_modification_allowed,omitempty" url:"-"`
	Force                         *bool  `json:"force,omitempty" url:"-"`
}
