// This file was auto-generated by Fern from our API Definition.

package accesscodes

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	errors "errors"
	seamapigo "github.com/seamapi/go"
	core "github.com/seamapi/go/core"
	io "io"
	http "net/http"
)

type UnmanagedClient interface {
	ConvertToManaged(ctx context.Context, request *AccessCodesUnmanagedConvertToManagedRequest) (*seamapigo.AccessCodesUnmanagedConvertToManagedResponse, error)
	Delete(ctx context.Context, request *AccessCodesUnmanagedDeleteRequest) (*seamapigo.AccessCodesUnmanagedDeleteResponse, error)
	Get(ctx context.Context, request *AccessCodesUnmanagedGetRequest) (*seamapigo.AccessCodesUnmanagedGetResponse, error)
	List(ctx context.Context, request *AccessCodesUnmanagedListRequest) (*seamapigo.AccessCodesUnmanagedListResponse, error)
	Update(ctx context.Context, request *AccessCodesUnmanagedUpdateRequest) (*seamapigo.AccessCodesUnmanagedUpdateResponse, error)
}

func NewUnmanagedClient(opts ...core.ClientOption) UnmanagedClient {
	options := core.NewClientOptions()
	for _, opt := range opts {
		opt(options)
	}
	return &unmanagedClient{
		baseURL:    options.BaseURL,
		httpClient: options.HTTPClient,
		header:     options.ToHeader(),
	}
}

type unmanagedClient struct {
	baseURL    string
	httpClient core.HTTPClient
	header     http.Header
}

func (u *unmanagedClient) ConvertToManaged(ctx context.Context, request *AccessCodesUnmanagedConvertToManagedRequest) (*seamapigo.AccessCodesUnmanagedConvertToManagedResponse, error) {
	baseURL := "https://connect.getseam.com"
	if u.baseURL != "" {
		baseURL = u.baseURL
	}
	endpointURL := baseURL + "/" + "access_codes/unmanaged/convert_to_managed"

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 400:
			value := new(BadRequestError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		case 401:
			value := new(UnauthorizedError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		}
		return apiError
	}

	var response *seamapigo.AccessCodesUnmanagedConvertToManagedResponse
	if err := core.DoRequest(
		ctx,
		u.httpClient,
		endpointURL,
		http.MethodPost,
		request,
		&response,
		false,
		u.header,
		errorDecoder,
	); err != nil {
		return response, err
	}
	return response, nil
}

func (u *unmanagedClient) Delete(ctx context.Context, request *AccessCodesUnmanagedDeleteRequest) (*seamapigo.AccessCodesUnmanagedDeleteResponse, error) {
	baseURL := "https://connect.getseam.com"
	if u.baseURL != "" {
		baseURL = u.baseURL
	}
	endpointURL := baseURL + "/" + "access_codes/unmanaged/delete"

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 400:
			value := new(BadRequestError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		case 401:
			value := new(UnauthorizedError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		}
		return apiError
	}

	var response *seamapigo.AccessCodesUnmanagedDeleteResponse
	if err := core.DoRequest(
		ctx,
		u.httpClient,
		endpointURL,
		http.MethodPost,
		request,
		&response,
		false,
		u.header,
		errorDecoder,
	); err != nil {
		return response, err
	}
	return response, nil
}

func (u *unmanagedClient) Get(ctx context.Context, request *AccessCodesUnmanagedGetRequest) (*seamapigo.AccessCodesUnmanagedGetResponse, error) {
	baseURL := "https://connect.getseam.com"
	if u.baseURL != "" {
		baseURL = u.baseURL
	}
	endpointURL := baseURL + "/" + "access_codes/unmanaged/get"

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 400:
			value := new(BadRequestError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		case 401:
			value := new(UnauthorizedError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		}
		return apiError
	}

	var response *seamapigo.AccessCodesUnmanagedGetResponse
	if err := core.DoRequest(
		ctx,
		u.httpClient,
		endpointURL,
		http.MethodPost,
		request,
		&response,
		false,
		u.header,
		errorDecoder,
	); err != nil {
		return response, err
	}
	return response, nil
}

func (u *unmanagedClient) List(ctx context.Context, request *AccessCodesUnmanagedListRequest) (*seamapigo.AccessCodesUnmanagedListResponse, error) {
	baseURL := "https://connect.getseam.com"
	if u.baseURL != "" {
		baseURL = u.baseURL
	}
	endpointURL := baseURL + "/" + "access_codes/unmanaged/list"

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 400:
			value := new(BadRequestError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		case 401:
			value := new(UnauthorizedError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		}
		return apiError
	}

	var response *seamapigo.AccessCodesUnmanagedListResponse
	if err := core.DoRequest(
		ctx,
		u.httpClient,
		endpointURL,
		http.MethodPost,
		request,
		&response,
		false,
		u.header,
		errorDecoder,
	); err != nil {
		return response, err
	}
	return response, nil
}

func (u *unmanagedClient) Update(ctx context.Context, request *AccessCodesUnmanagedUpdateRequest) (*seamapigo.AccessCodesUnmanagedUpdateResponse, error) {
	baseURL := "https://connect.getseam.com"
	if u.baseURL != "" {
		baseURL = u.baseURL
	}
	endpointURL := baseURL + "/" + "access_codes/unmanaged/update"

	errorDecoder := func(statusCode int, body io.Reader) error {
		raw, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		apiError := core.NewAPIError(statusCode, errors.New(string(raw)))
		decoder := json.NewDecoder(bytes.NewReader(raw))
		switch statusCode {
		case 400:
			value := new(BadRequestError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		case 401:
			value := new(UnauthorizedError)
			value.APIError = apiError
			if err := decoder.Decode(value); err != nil {
				return err
			}
			return value
		}
		return apiError
	}

	var response *seamapigo.AccessCodesUnmanagedUpdateResponse
	if err := core.DoRequest(
		ctx,
		u.httpClient,
		endpointURL,
		http.MethodPost,
		request,
		&response,
		false,
		u.header,
		errorDecoder,
	); err != nil {
		return response, err
	}
	return response, nil
}
